# Exact copy from a blog post: http://rockyj.in/2014/09/14/jruby_docker.html
# This did not contain a license.

FROM phusion/baseimage:0.9.13

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

#Install Oracle JDK 8 and Node.js
RUN sudo add-apt-repository ppa:webupd8team/java
RUN sudo add-apt-repository ppa:chris-lea/node.js && sudo apt-get update
#This absurdity exists so that JDK is installed without prompting for license
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

RUN sudo apt-get install -y --no-install-recommends oracle-java8-installer
RUN sudo apt-get install oracle-java8-set-default
RUN sudo apt-get install -y nodejs
RUN sudo apt-get autoremove -y && apt-get clean

ENV JRUBY_VERSION 1.7.15
#Get JRuby
RUN curl http://jruby.org.s3.amazonaws.com/downloads/$JRUBY_VERSION/jruby-bin-$JRUBY_VERSION.tar.gz | tar xz -C /opt

ENV PATH /opt/jruby-$JRUBY_VERSION/bin:$PATH

RUN echo gem: --no-document >> /etc/gemrc

RUN gem update --system
RUN gem install bundler

#Add user
RUN addgroup --gid 9999 app
RUN adduser --uid 9999 --gid 9999 --disabled-password --gecos "Application" app
RUN usermod -L app
RUN mkdir -p /home/app/my_app
ADD . /home/app/my_app
RUN chown -R app:app /home/app/

USER app

#JRuby options
ENV PATH /opt/jruby-$JRUBY_VERSION/bin:$PATH
RUN echo compat.version=2.0 > /home/app/.jrubyrc
RUN echo invokedynamic.all=true >> /home/app/.jrubyrc

#Get Rails running
WORKDIR /home/app/my_app
ENV RAILS_ENV staging
RUN bundle exec rake db:reset
RUN bundle install --deployment --without test development
##################################################################
#Remove these lines when using fig since fog will start the server
##################################################################
RUN bundle exec rake db:reset
EXPOSE 3000
ENTRYPOINT bundle exec rails server
