# Modified from a blog post: http://rockyj.in/2014/09/14/jruby_docker.html
# This did not contain a license.

FROM debian:7.8 
#FROM phusion/baseimage:0.9.13

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init system.
# CMD ["/sbin/my_init"]

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
      curl git vim \ 
        # utilities
      openjdk-7-jre \
      mysql-server-5.5 

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh && \
    echo '\nPATH=$PATH:/root/.nvm' >> ~/.bashrc && \
    /bin/bash -ci 'nvm install 0.10.33' && \
    /bin/bash -ci 'nvm alias default 0.10.33'
  # Install a version of nodejs.
  # (nvm) installation.
  # Set a version of nodejs as default. (Not sure if this persists through logout/login).

ENV JRUBY_VERSION 1.7.18
RUN curl http://jruby.org.s3.amazonaws.com/downloads/$JRUBY_VERSION/jruby-bin-$JRUBY_VERSION.tar.gz | tar xz -C /opt
ENV PATH /opt/jruby-$JRUBY_VERSION/bin:$PATH
  # Get JRuby

RUN echo gem: --no-document >> /etc/gemrc
RUN gem update --system
RUN gem install bundler

#Add user
RUN addgroup --gid 9999 app
RUN adduser --uid 9999 --gid 9999 --disabled-password --gecos "Application" app
RUN usermod -L app
RUN mkdir -p /home/app/my_app
# ADD . /home/app/my_app
RUN chown -R app:app /home/app/

# USER app
RUN gem install rails 
RUN echo '\nservice mysql start' >> ~/.bashrc 
RUN cd /home/app && rails new my_app -d mysql

#JRuby options
ENV PATH /opt/jruby-$JRUBY_VERSION/bin:$PATH
RUN echo compat.version=2.0 > /home/app/.jrubyrc
RUN echo invokedynamic.all=true >> /home/app/.jrubyrc

RUN apt-get autoremove -y && apt-get clean
  # Cleanup.

#Get Rails running
WORKDIR /home/app/my_app
# ENV RAILS_ENV staging
RUN bundle exec rake db:create
RUN bundle install --deployment --without test development
##################################################################
#Remove these lines when using fig since fog will start the server
##################################################################
# RUN bundle exec rake db:reset
EXPOSE 3000
ENTRYPOINT bundle exec rails server -b 0.0.0.0
