var Vips = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var l=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,r=ea&&self.name?.startsWith("em-pthread");l.dynamicLibraries=l.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];l.workaroundCors&&(l.mainScriptUrlOrBlob=l.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var fa=[],ha="./this.program";ea&&(_scriptName=self.location.href);var ja="";
function la(a){return l.locateFile?l.locateFile(a,ja):ja+a}var ma,na;if(da||ea){try{ja=(new URL(".",_scriptName)).href}catch{}ea&&(na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ma=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var oa=console.log.bind(console),v=console.error.bind(console),pa=[],qa,ra,sa,ta=!1,ua,w,x,z,A,B,D,va,E,wa,xa,ya=!1,Aa=!1;class F extends Error{}class Ba extends F{}class Ca extends F{constructor(a){super(a);this.va=a;a=Da(a);this.name=a[0];this.message=a[1]}}var Ea={};
if(r){var Fa,Ga=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.T;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({T:"loaded"});for(let f of e)a(f);self.onmessage=a};pa=c.zb;Ea=c.jc;for(const f of c.Kb)if(!l[f]||l[f].proxy)l[f]=(...g)=>{postMessage({T:"callHandler",Jb:f,sb:g})},"print"==f&&(oa=l[f]),"printErr"==f&&(v=l[f]);ra=c.qc;Ha();Fa(c.rc)}else if("run"===d){Ia(c.W);Ja(c.W,0,0,1,0,0);Ka();La(c.W);Ga||(Ma(),Ga=!0);try{Na(c.mc,
c.Da)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Ga&&Oa():d&&(v(`worker: received unknown command ${d}`),v(c)))}catch(e){throw Qa(),e;}}self.onmessage=a}function Ha(){var a=ra.buffer;w=new Int8Array(a);z=new Int16Array(a);x=new Uint8Array(a);A=new Uint16Array(a);B=new Int32Array(a);D=new Uint32Array(a);va=new Float32Array(a);xa=new Float64Array(a);E=new BigInt64Array(a);wa=new BigUint64Array(a)}var Ra=[];
function Sa(){ya=!0;r?startWorker(l):(Ta(Ra),l.noFSInit||FS.Ga||FS.init(),G.__wasm_call_ctors(),Ta(Ua),FS.bb=!1)}var Va=0,Wa=null;function Xa(){Va++;l.monitorRunDependencies?.(Va)}function Ya(){Va--;l.monitorRunDependencies?.(Va);if(0==Va&&Wa){var a=Wa;Wa=null;a()}}function Za(a){l.onAbort?.(a);a="Aborted("+a+")";v(a);ta=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var $a;
async function ab(a){if(!qa)try{var b=await ma(a);return new Uint8Array(b)}catch{}if(a==$a&&qa)a=new Uint8Array(qa);else if(na)a=na(a);else throw"both async and sync fetching of the wasm failed";return a}async function bb(a,b){try{var c=await ab(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),Za(d)}}
async function cb(a){var b=$a;if(!qa&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return bb(b,a)}
function db(){H={__assert_fail:eb,__call_sighandler:fb,__cxa_begin_catch:gb,__cxa_end_catch:hb,__cxa_find_matching_catch_2:ib,__cxa_find_matching_catch_3:jb,__cxa_rethrow:kb,__cxa_throw:lb,__cxa_uncaught_exceptions:mb,__heap_base:nb,__indirect_function_table:ob,__lsan_ignore_object:pb,__memory_base:qb,__pthread_create_js:rb,__resumeException:sb,__stack_high:tb,__stack_low:ub,__stack_pointer:vb,__syscall_dup:wb,__syscall_faccessat:xb,__syscall_fcntl64:yb,__syscall_fstat64:zb,__syscall_ftruncate64:Ab,
__syscall_getcwd:Bb,__syscall_ioctl:Cb,__syscall_lstat64:Db,__syscall_newfstatat:Eb,__syscall_openat:Fb,__syscall_poll:Gb,__syscall_rmdir:Hb,__syscall_stat64:Ib,__syscall_unlinkat:Jb,__table_base:Kb,_abort_js:Lb,_dlopen_js:Mb,_dlsym_catchup_js:Nb,_dlsym_js:Ob,_embind_finalize_value_object:Pb,_embind_register_arithmetic_vector:Qb,_embind_register_bigint:Rb,_embind_register_bool:Sb,_embind_register_class:Tb,_embind_register_class_class_function:Ub,_embind_register_class_constructor:Vb,_embind_register_class_function:Wb,
_embind_register_class_property:Xb,_embind_register_emval:Yb,_embind_register_enum:Zb,_embind_register_enum_value:$b,_embind_register_float:ac,_embind_register_function:bc,_embind_register_integer:cc,_embind_register_memory_view:dc,_embind_register_std_string:ec,_embind_register_std_wstring:fc,_embind_register_value_object:gc,_embind_register_value_object_field:hc,_embind_register_void:ic,_emscripten_dlopen_js:jc,_emscripten_dlsync_threads:kc,_emscripten_dlsync_threads_async:lc,_emscripten_get_dynamic_libraries_js:mc,
_emscripten_init_main_thread_js:nc,_emscripten_notify_mailbox_postmessage:oc,_emscripten_receive_on_main_thread_js:pc,_emscripten_runtime_keepalive_clear:qc,_emscripten_thread_cleanup:rc,_emscripten_thread_exit_joinable:sc,_emscripten_thread_mailbox_await:La,_emscripten_thread_set_strongref:tc,_emscripten_throw_longjmp:uc,_emval_as:vc,_emval_call:wc,_emval_decref:xc,_emval_get_global:yc,_emval_get_method_caller:zc,_emval_get_module_property:Ac,_emval_get_property:Bc,_emval_incref:Cc,_emval_instanceof:Dc,
_emval_is_number:Ec,_emval_is_string:Fc,_emval_new_cstring:Gc,_emval_run_destructors:Hc,_emval_set_property:Ic,_emval_take_value:Jc,_emval_typeof:Kc,_gmtime_js:Lc,_localtime_js:Mc,_mmap_js:Nc,_munmap_js:Oc,_tzset_js:Pc,clock_time_get:Qc,emscripten_check_blocking_allowed:Rc,emscripten_date_now:Sc,emscripten_err:Tc,emscripten_exit_with_live_runtime:Uc,emscripten_get_heap_max:Vc,emscripten_get_now:Wc,emscripten_num_logical_cores:Xc,emscripten_promise_destroy:Yc,emscripten_promise_resolve:Zc,emscripten_resize_heap:$c,
environ_get:ad,environ_sizes_get:bd,exit:cd,fd_close:dd,fd_fdstat_get:ed,fd_read:fd,fd_seek:gd,fd_write:hd,ffi_call_js:jd,heif_error_success:kd,heif_image_get_bits_per_pixel_range:ld,heif_image_get_chroma_format:md,heif_image_get_nclx_color_profile:nd,heif_image_get_plane_readonly:od,heif_image_release:pd,heif_nclx_color_profile_free:qd,invoke_di:rd,invoke_dii:sd,invoke_diii:td,invoke_diiii:ud,invoke_fiii:vd,invoke_i:wd,invoke_ii:xd,invoke_iii:yd,invoke_iiid:zd,invoke_iiii:Ad,invoke_iiiii:Bd,invoke_iiiiid:Cd,
invoke_iiiiii:Dd,invoke_iiiiiii:Ed,invoke_iiiiiiii:Fd,invoke_iiiiiiiiiii:Gd,invoke_iiiiiiiiiiii:Hd,invoke_iiiiiiiiiiiii:Id,invoke_iiiiij:Jd,invoke_ji:Kd,invoke_jiiii:Ld,invoke_v:Md,invoke_vi:Nd,invoke_vid:Od,invoke_viddi:Pd,invoke_vii:Qd,invoke_viid:Rd,invoke_viidd:Sd,invoke_viiddi:Td,invoke_viidi:Ud,invoke_viii:Vd,invoke_viiid:Wd,invoke_viiidddddi:Xd,invoke_viiiddddi:Yd,invoke_viiidddi:Zd,invoke_viiiddi:$d,invoke_viiidi:ae,invoke_viiii:be,invoke_viiiii:ce,invoke_viiiiii:de,invoke_viiiiiii:ee,invoke_viiiiiiii:fe,
invoke_viiiiiiiii:ge,invoke_viiiiiiiiii:he,invoke_viiiiiiiiiii:ie,invoke_viiiiiiiiiiii:je,invoke_viiiiiiiiiiiii:ke,invoke_viiiiiiiiiiiiiii:le,llvm_eh_typeid_for:me,memory:ra,proc_exit:ne,random_get:oe};return{env:H,wasi_snapshot_preview1:H,"GOT.mem":new Proxy(H,pe),"GOT.func":new Proxy(H,pe)}}var re=a=>{if(!(a instanceof qe||"unwind"==a))throw a;};class qe{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var J=0,se=a=>{a.terminate();a.onmessage=()=>{}},ze=a=>{var b=te[a];ue.delete(a);a in ve&&ve[a].resolve();a=b.W;delete te[a];we.push(b);xe.splice(xe.indexOf(b),1);b.W=0;ye(a)},Ta=a=>{for(;0<a.length;)a.shift()(l)},Ae=[],De=a=>{0==we.length&&(Be(),Ce(we[0]));var b=we.pop();if(!b)return 6;xe.push(b);te[a.W]=b;b.W=a.W;b.postMessage({T:"run",mc:a.lc,Da:a.Da,W:a.W},a.mb);return 0},we=[],xe=[],Ee=[],te={};
function Fe(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Be();Ae.push(()=>{Xa("loading-workers");Ge(()=>Ya("loading-workers"))});ve={};ue=new Set}var He=()=>{for(var a of xe)se(a);for(a of we)se(a);we=[];xe=[];te={}};function Ka(){Ee.forEach(a=>a())}
var Ce=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.T;if(f.Ca&&f.Ca!=Ie()){var h=te[f.Ca];h?h.postMessage(f,f.mb):v(`Internal error! Worker sent a message "${g}" to target pthread ${f.Ca}, but that thread no longer exists!`)}else if("checkMailbox"===g)Oa();else if("spawnThread"===g)De(f);else if("cleanupThread"===g)ze(f.Qa);else if("markAsFinished"===g)f=f.Qa,ue.add(f),f in ve&&ve[f].resolve();else if("loaded"===g)a.loaded=!0,b(a);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===
g)l[f.Jb](...f.sb);else g&&v(`worker sent an unknown command ${g}`)};a.onerror=f=>{v(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)l.propertyIsEnumerable(e)&&c.push(e);a.postMessage({T:"load",Kb:c,qc:ra,rc:sa,zb:pa,jc:Ea})});function Ge(a){r?a():Promise.all(we.map(Ce)).then(a)}
function Be(){var a=_scriptName;l.mainScriptUrlOrBlob&&(a=l.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{name:"em-pthread"});we.push(a)}var ue,ve,P=(a,b,...c)=>{for(var d=2*c.length,e=K(),f=Je(8*d),g=f>>3,h=0;h<c.length;h++){var k=c[h];"bigint"==typeof k?(E[g+2*h]=1n,E[g+2*h+1]=k):(E[g+2*h]=0n,xa[g+2*h+1]=k)}a=Ke(a,0,d,f,b);N(e);return a};function ne(a){if(r)return P(0,1,a);ua=a;Le||0<J||(He(),l.onExit?.(a),ta=!0);throw new qe(a);}ne.g="vi";
function Me(a){if(r)return P(1,0,a);cd(a)}var cd=a=>{ua=a;if(r)throw Me(a),"unwind";if(!(Le||0<J||r)){Ne();FS.Ga=!1;Oe(0);for(var b of FS.streams)b&&FS.close(b);He();Aa=!0}ne(a)};cd.g="vi";var Qe=a=>{if(!Aa&&!ta)try{if(a(),!(Aa||Le||0<J))try{r?Pe(ua):cd(ua)}catch(b){re(b)}}catch(b){re(b)}},Re=a=>{J+=1;setTimeout(()=>{--J;Qe(a)},1E4)},Se=[],Te={},Ue=!1,Ve=!1,We=[];
function Xe(){function a(){var c=l.canvas;Ve=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ye){Ye=!0;Se.push({canHandle:function(c){return!l.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Ze(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Ze(d)}));var h=URL.createObjectURL(g),k=new Image;k.onload=()=>{var m=document.createElement("canvas");
m.width=k.width;m.height=k.height;m.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(h);e?.(c)};k.onerror=()=>{v(`Image ${h} could not be decoded`);f?.()};k.src=h}});Se.push({canHandle:function(c){return!l.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:Ze(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=function(){if(!g){v(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var m="",p=0,n=0,q=0;q<c.length;q++)for(p=p<<8|c[q],n+=8;6<=n;){var t=p>>n-6&63;n-=6;m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[t]}2==n?(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&3)<<4],m+="=="):4==n&&(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&15)<<2],m+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+m;f(k)}};k.src=h;Re(()=>{f(k)})}});var b=l.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),l.elementPointerLock&&b.addEventListener("click",
c=>{!Ve&&l.canvas.requestPointerLock&&(l.canvas.requestPointerLock(),c.preventDefault())},!1))}}var $e=!1,af=void 0,bf=void 0;function cf(){if(!Ue)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}
function Ze(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var df=[];function ef(){var a=l.canvas;df.forEach(b=>b(a.width,a.height))}
function ff(a,b,c){b&&c?(a.sc=b,a.Lb=c):(b=a.sc,c=a.Lb);var d=b,e=c;0<l.forcedAspectRatio&&(d/e<l.forcedAspectRatio?d=Math.round(e*l.forcedAspectRatio):e=Math.round(d/l.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}bf?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var gf={},Ye,hf={},jf=new Set(["__lsan_ignore_object","__lsan_ignore_object"]),pe={get(a,b){(a=hf[b])||(a=hf[b]=new WebAssembly.Global({value:"i32",mutable:!0}));jf.has(b)||(a.required=!0);return a}},kf=[],Ia=a=>{var b=D[a+52>>2];lf(b,b-D[a+56>>2]);N(b)},mf=new TextDecoder,nf=(a,b=0,c=NaN)=>{c=b+c;for(var d=b;a[d]&&!(d>=c);)++d;return mf.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,d):a.slice(b,d):new Uint8Array(a.slice(b,d)))},of=a=>{function b(){for(var n=0,q=1;;){var t=a[f++];n+=
(t&127)*q;q*=128;if(!(t&128))break}return n}function c(){var n=b();f+=n;return nf(a,f-n,n)}function d(){for(var n=b(),q=[];n--;)q.push(c());return q}function e(n,q){if(n)throw Error(q);}var f=0,g=0;if(a instanceof WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");
f=9;g=b();g=f+g;var h=c();e("dylink.0"!==h)}for(h={La:[],lb:new Set,nb:new Set,ec:[]};f<g;){var k=a[f++],m=b();if(1===k)h.Ka=b(),h.Ub=b(),h.sa=b(),h.Pc=b();else if(2===k)h.La=d();else if(3===k)for(k=b();k--;){m=c();var p=b();p&256&&h.lb.add(m)}else if(4===k)for(k=b();k--;)c(),m=c(),p=b(),1==(p&3)&&h.nb.add(m);else 5===k?h.ec=d():f+=m}return h},pf=[],ob=new WebAssembly.Table({initial:5908,element:"anyfunc"}),Q=a=>{var b=pf[a];b||(pf[a]=b=ob.get(a));return b},Na=(a,b)=>{Le=J=0;qf();a=Q(a)(b);Le||0<
J?ua=a:Pe(a)},tf=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};rf[a]=c;void 0!=b&&(sf[b]=c);return c},rf={},sf={},nb=3682288,uf=(a,b)=>Math.ceil(a/b)*b,wf=a=>{if(ya)return vf(a,1);var b=nb;nb=a=b+16*Math.ceil(a/16);hf.__heap_base.value=a;return b},yf=(a,b)=>{if(xf)for(var c=a;c<a+b;c++){var d=Q(c);d&&xf.set(d,c)}},xf,zf=a=>{xf||(xf=new WeakMap,yf(0,ob.length));return xf.get(a)||0},Af=[],Bf=(a,b)=>{var c=zf(a);if(c)return c;if(Af.length)c=Af.pop();else{try{ob.grow(1)}catch(k){if(!(k instanceof
RangeError))throw k;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=ob.length-1}try{var d=c;ob.set(d,a);pf[d]=ob.get(d)}catch(k){if(!(k instanceof TypeError))throw k;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;for(var e={i:"i32",j:"i64",f:"f32",d:"f64",e:"externref",p:"i32"},f={parameters:[],results:"v"==b[0]?[]:[e[b[0]]]},g=1;g<b.length;++g)f.parameters.push(e[b[g]]);b=new d(f,a)}else{d=[1];f=b.slice(0,1);b=b.slice(1);g={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);
var h=b.length;128>h?d.push(h):d.push(h%128|128,h>>7);for(e of b)d.push(g[e]);"v"==f?d.push(0):d.push(1,g[f]);b=[0,97,115,109,1,0,0,0,1];e=d.length;128>e?b.push(e):b.push(e%128|128,e>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}d=c;ob.set(d,b);pf[d]=ob.get(d)}xf.set(a,c);return c},Cf=(a,b,c)=>{var d={},e;for(e in a){var f=a[e];"object"==typeof f&&(f=f.value);"number"==typeof f&&(f+=b);
d[e]=f}for(var g in d){a=g;if("__cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(a)||a.startsWith("__em_js__"))continue;a=d[g];let h,k;(h=hf)[k=g]||(h[k]=new WebAssembly.Global({value:"i32",mutable:!0}));if(c||0==hf[g].value)"function"==typeof a?hf[g].value=Bf(a):"number"==typeof a?hf[g].value=a:v(`unhandled export type for '${g}': ${typeof a}`)}return d},
Df=a=>{a=H[a];return!a||a.Y?!1:!0},Ef=(a,b=[])=>Q(a)(...b),Ff=a=>(b,...c)=>{var d=K();try{return Ef(b,c)}catch(e){N(d);if(!(e instanceof F))throw e;R(1,0);if("j"==a[0])return 0n}},Hf=a=>{var b;Df(a)?b=H[a]:a.startsWith("invoke_")?b=H[a]=Ff(a.split("_")[1]):a.startsWith("__cxa_find_matching_catch_")&&(b=H[a]=(...c)=>Gf(c));return{Pa:b,name:a}},Ua=[],S=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&x[c];)++c;return mf.decode(x.slice(a,c))},Mf=(a,b,c,d,e)=>{function f(){function h(y,C){function L(za,
ia){za=[];for(var Pa=0;16>Pa;Pa++)if(-1!=ia.indexOf("$"+Pa))za.push("$"+Pa);else break;za=za.join(",");If[I]=eval(`(${za}) => { ${ia} };`)}function M(za,ia,Pa){var Nf=[];ia=ia.slice(1,-1);if("void"!=ia){ia=ia.split(",");for(var ai in ia){var bi=ia[ai].split(" ").pop();Nf.push(bi.replace("*",""))}}q[za]=eval(`(${Nf}) => ${Pa};`)}!r&&c&&(Ea[c]=y);yf(n,g.sa);q=Cf(C.exports,p);b.rb||Jf();if("__start_em_asm"in q){var I=q.__start_em_asm;for(y=q.__stop_em_asm;I<y;){var ka=S(I);L(I,ka);I=x.indexOf(0,I)+1}}for(var O in q)O.startsWith("__em_js__")&&
(I=q[O],ka=S(I),y=ka.split("<::>"),M(O.replace("__em_js__",""),y[0],y[1]),delete q[O]);Kf(q._emscripten_tls_init,C.exports,g);k&&((C=q.__wasm_apply_data_relocs)&&(ya?C():Ra.push(C)),(C=q.__wasm_call_ctors)&&(ya?C():Ua.push(C)));return q}var k=!e||!w[e+8];if(k){var m=Math.pow(2,g.Ub),p=g.Ka?uf(wf(g.Ka+m),m):0,n=g.sa?ob.length:0;e&&(w[e+8]=1,D[e+12>>2]=p,B[e+16>>2]=g.Ka,D[e+20>>2]=n,B[e+24>>2]=g.sa)}else p=D[e+12>>2],n=D[e+20>>2];g.sa&&ob.grow(g.sa);var q;m=new Proxy({},{get(y,C){switch(C){case "__memory_base":return p;
case "__table_base":return n}if(C in H&&!H[C].Y)return H[C];if(!(C in y)){var L;y[C]=(...M)=>{if(!L){var I=Hf(C).Pa;!I&&d&&(I=d[C]);I||=q[C];L=I}return L(...M)}}return y[C]}});var t={"GOT.mem":new Proxy({},pe),"GOT.func":new Proxy({},pe),env:m,wasi_snapshot_preview1:m};if(b.G)return(async()=>{var y;a instanceof WebAssembly.Module?y=new WebAssembly.Instance(a,t):{module:a,instance:y}=await WebAssembly.instantiate(a,t);return h(a,y)})();m=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);
var u=new WebAssembly.Instance(m,t);return h(m,u)}var g=of(a);jf=g.nb;if(b.G)return g.La.reduce((h,k)=>h.then(()=>Lf(k,b,d)),Promise.resolve()).then(f);g.La.forEach(h=>Lf(h,b,d));return f()},Of=a=>{var b,c;for([b,c]of Object.entries(a))Df(b)||(H[b]=c)},Pf=async a=>{a=await ma(a);return new Uint8Array(a)};
function Lf(a,b={global:!0,oa:!0},c,d){function e(){var k=Ea[a];if(k)return b.G?Promise.resolve(k):k;if(d){k=D[d+28>>2];var m=D[d+32>>2];if(k&&m)return k=w.slice(k,k+m),b.G?Promise.resolve(k):k}k=la(a);if(b.G)return Pf(k);if(!na)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return na(k)}function f(){var k=Te[a];return k?b.G?Promise.resolve(k):k:b.G?e().then(m=>Mf(m,b,a,c,d)):Mf(e(),b,a,c,d)}function g(k){h.global?Of(k):c&&Object.assign(c,k);h.exports=
k}var h=rf[a];if(h)return b.global?h.global||(h.global=!0,Of(h.exports)):c&&Object.assign(c,h.exports),b.oa&&Infinity!==h.Aa&&(h.Aa=Infinity),h.Aa++,d&&(sf[d]=h),b.G?Promise.resolve(!0):!0;h=tf(a,d,"loading");h.Aa=b.oa?Infinity:1;h.global=b.global;if(b.G)return f().then(k=>{g(k);return!0});g(f());return!0}
var Jf=()=>{var a,b;for([a,b]of Object.entries(hf))if(0==b.value){var c=Hf(a).Pa;if(c||b.required)if("function"==typeof c)b.value=Bf(c,c.g);else if("number"==typeof c)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c}`);}},Qf=()=>{pa.length?(Xa("loadDylibs"),pa.reduce((a,b)=>a.then(()=>Lf(b,{G:!0,global:!0,oa:!0,rb:!0})),Promise.resolve()).then(()=>{Jf();Ya("loadDylibs")})):Jf()},Le=!1,Kf=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.lb.forEach(g=>f[g]=b[g]);Cf(f,e,!0)}}Ee.push(d);
ya&&d()},eb=(a,b,c,d)=>Za(`Assertion failed: ${S(a)}, at: `+[b?S(b):"unknown filename",c,d?S(d):"unknown function"]);eb.g="vppip";var fb=(a,b)=>Q(a)(b);fb.g="vpi";var Rf=[],Sf=0,gb=a=>{var b=new Tf(a);0==w[b.s+12]&&(w[b.s+12]=1,Sf--);w[b.s+13]=0;Rf.push(b);Uf(a);return Vf(a)};gb.g="pp";var Wf=0,hb=()=>{R(0,0);var a=Rf.pop();Xf(a.va);Wf=0};hb.g="v";class Tf{constructor(a){this.va=a;this.s=a-24}init(a,b){D[this.s+16>>2]=0;D[this.s+4>>2]=a;D[this.s+8>>2]=b}}
var Gf=a=>{var b=Wf?.va;if(!b)return Yf(0),0;var c=new Tf(b);D[c.s+16>>2]=b;var d=D[c.s+4>>2];if(!d)return Yf(0),b;for(var e of a){if(0===e||e===d)break;if(Zf(e,d,c.s+16))return Yf(e),b}Yf(d);return b},ib=()=>Gf([]);ib.g="p";var jb=a=>Gf([a]);jb.g="pp";var kb=()=>{var a=Rf.pop();a||Za("no exception to throw");var b=a.va;0==w[a.s+13]&&(Rf.push(a),w[a.s+13]=1,w[a.s+12]=0,Sf++);Wf=new Ca(b);throw Wf;};kb.g="v";var lb=(a,b,c)=>{(new Tf(a)).init(b,c);Wf=new Ca(a);Sf++;throw Wf;};lb.g="vppp";
var mb=()=>Sf;mb.g="i";function pb(...a){return H.__lsan_ignore_object(...a)}pb.Y=!0;var qb=new WebAssembly.Global({value:"i32",mutable:!1},1024);function $f(a,b,c,d){return r?P(2,1,a,b,c,d):rb(a,b,c,d)}var rb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return $f(a,b,c,d);a={lc:c,W:a,Da:d,mb:e};return r?(a.T="spawnThread",postMessage(a,e),0):De(a)};rb.g="ipppp";var sb=a=>{Wf||=new Ca(a);throw Wf;};sb.g="vp";
var tb=3682288,ub=3420144,vb=new WebAssembly.Global({value:"i32",mutable:!0},3682288),ag=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},bg=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=ag(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},cg=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=
b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},dg=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],eg=(a,b)=>bg(a+"/"+b),fg=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),gg=a=>{(gg=fg())(a)},hg=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=ag(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ig=(a,
b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=hg(a).slice(1);b=hg(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},jg=[],kg=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
lg=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},mg=a=>{var b=Array(kg(a)+1);a=lg(a,b,0,b.length);b.length=a;return b},ng=[];
function og(a,b){ng[a]={input:[],output:[],ba:b};FS.registerDevice(a,pg)}
var pg={open(a){var b=ng[a.node.qa];if(!b)throw new FS.h(43);a.B=b;a.seekable=!1},close(a){a.B.ba.xa(a.B)},xa(a){a.B.ba.xa(a.B)},read(a,b,c,d){if(!a.B||!a.B.ba.ab)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.B.ba.ab(a.B)}catch(h){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Z=Date.now());return e},write(a,b,c,d){if(!a.B||!a.B.ba.Na)throw new FS.h(60);try{for(var e=0;e<d;e++)a.B.ba.Na(a.B,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.M=a.node.L=Date.now());return e}},qg={ab(){a:{if(!jg.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}jg=mg(a)}a=jg.shift()}return a},Na(a,b){null===b||10===b?(oa(nf(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(oa(nf(a.output)),a.output=[])},Ob(){return{zc:25856,Bc:5,yc:191,Ac:35387,xc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0]}},Pb(){return 0},Qb(){return[24,80]}},rg={Na(a,b){null===b||10===b?(v(nf(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(v(nf(a.output)),a.output=[])}},tg=a=>{a=65536*Math.ceil(a/65536);var b=sg(65536,a);b&&x.fill(0,b,b+a);return b},T={V:null,mount(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);T.V||(T.V={dir:{node:{P:T.m.P,S:T.m.S,ha:T.m.ha,aa:T.m.aa,rename:T.m.rename,unlink:T.m.unlink,
rmdir:T.m.rmdir,ra:T.m.ra,symlink:T.m.symlink},stream:{llseek:T.o.llseek}},file:{node:{P:T.m.P,S:T.m.S},stream:{llseek:T.o.llseek,read:T.o.read,write:T.o.write,ia:T.o.ia,ka:T.o.ka}},link:{node:{P:T.m.P,S:T.m.S,readlink:T.m.readlink},stream:{}},Sa:{node:{P:T.m.P,S:T.m.S},stream:FS.vb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=T.V.dir.node,c.o=T.V.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=T.V.file.node,c.o=T.V.file.stream,c.D=0,c.u=null):FS.isLink(c.mode)?(c.m=T.V.link.node,c.o=T.V.link.stream):
FS.isChrdev(c.mode)&&(c.m=T.V.Sa.node,c.o=T.V.Sa.stream);c.Z=c.M=c.L=Date.now();a&&(a.u[b]=c,a.Z=a.M=a.L=c.Z);return c},Ic(a){return a.u?a.u.subarray?a.u.subarray(0,a.D):new Uint8Array(a.u):new Uint8Array(0)},m:{P(a){var b={};b.xb=FS.isChrdev(a.mode)?a.id:1;b.Nb=a.id;b.mode=a.mode;b.Vb=1;b.uid=0;b.Ib=0;b.qa=a.qa;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.D:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.Z=new Date(a.Z);b.M=new Date(a.M);b.L=new Date(a.L);b.tb=4096;b.Ra=Math.ceil(b.size/
b.tb);return b},S(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.D!=b&&(0==b?(a.u=null,a.D=0):(c=a.u,a.u=new Uint8Array(b),c&&a.u.set(c.subarray(0,Math.min(b,a.D))),a.D=b)))},ha(){throw T.Wa;},aa(a,b,c,d){return T.createNode(a,b,c,d)},rename(a,b,c){try{var d=ug(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);vg(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.L=b.M=a.parent.L=a.parent.M=Date.now()},unlink(a,b){delete a.u[b];
a.L=a.M=Date.now()},rmdir(a,b){var c=ug(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.L=a.M=Date.now()},ra(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){var f=a.node.u;if(e>=a.node.D)return 0;a=Math.min(a.node.D-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.M=a.L=Date.now();if(b.subarray&&(!a.u||a.u.subarray)){if(f)return a.u=b.subarray(c,c+d),a.D=d;if(0===a.D&&0===e)return a.u=b.slice(c,c+d),a.D=d;if(e+d<=a.D)return a.u.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.u?a.u.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.u,a.u=new Uint8Array(f),0<a.D&&a.u.set(g.subarray(0,a.D),0));if(a.u.subarray&&b.subarray)a.u.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.u[e+f]=b[c+f];a.D=Math.max(a.D,e+d);return d},llseek(a,b,c){1===
c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.D);if(0>b)throw new FS.h(28);return b},ia(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||!a||a.buffer!==w.buffer){d=!0;e=tg(b);if(!e)throw new FS.h(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);w.set(a,e)}}else d=!1,e=a.byteOffset;return{s:e,ca:d}},ka(a,b,c,d){T.o.write(a,b,0,d,c,!1);return 0}}},wg=(a,b,c,d)=>{"undefined"!=typeof gf&&Xe();var e=!1;Se.forEach(f=>
{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},xg=(a,b,c,d,e,f,g,h,k,m)=>{function p(t){function u(y){m?.();h||FS.createDataFile(a,b,y,d,e,k);f?.();Ya(q)}wg(t,n,u,()=>{g?.();Ya(q)})||u(t)}var n=b?hg(bg(a+"/"+b)):a,q=`cp ${n}`;Xa(q);"string"==typeof c?Pf(c).then(p,g):p(c)},yg=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function ug(a,b){var c=FS.isDir(a.mode)?(c=zg(a,"x"))?c:a.m.ha?0:2:54;if(c)throw new FS.h(c);for(c=FS.U[Ag(a.id,b)];c;c=c.ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ha(a,b)}function vg(a){var b=Ag(a.parent.id,a.name);if(FS.U[b]===a)FS.U[b]=a.ja;else for(b=FS.U[b];b;){if(b.ja===a){b.ja=a.ja;break}b=b.ja}}function Ag(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.U.length}function Bg(a){var b=Ag(a.parent.id,a.name);a.ja=FS.U[b];FS.U[b]=a}
function Cg(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zg(a,b){if(FS.bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Dg(a,b){if(!FS.isDir(a.mode))return 54;try{return ug(a,b),20}catch(c){}return zg(a,"wx")}
function Eg(a,b,c){try{var d=ug(a,b)}catch(e){return e.A}if(a=zg(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.ma(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Fg(a,b){if(!a)throw new FS.h(b);return a}function U(a){a=FS.$a(a);if(!a)throw new FS.h(8);return a}function Gg(a,b=-1){a=Object.assign(new FS.pb,a);if(-1==b)a:{for(b=0;b<=FS.qb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.$=b;return FS.streams[b]=a}
function Hg(a,b=-1){a=Gg(a,b);a.o?.Dc?.(a);return a}function Ig(a,b,c){var d=a?.o.S;a=d?a:b;d??=b.m.S;Fg(d,63);d(a,c)}function Jg(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.na)}return b}function Kg(a){var b={wc:4096,Gc:4096,Ra:1E6,vc:5E5,uc:5E5,files:FS.Ma,Ec:FS.Ma-1,Hc:42,flags:2,Nc:255};a.m.kb&&Object.assign(b,a.m.kb(a.mount.Xb.root));return b}function Lg(a,b,c,d){Ig(a,b,{mode:c&4095|b.mode&-4096,L:Date.now(),Xa:d})}
function Mg(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=zg(b,"w");if(d)throw new FS.h(d);Ig(a,b,{size:c,timestamp:Date.now()})}function Ng(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=bg(a+"/"+b);return FS.create(b,yg(c,d))}
function Og(a){if(!(a.Rb||a.Sb||a.link||a.u)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.u=na(a.url),a.D=a.u.length}catch(b){throw new FS.h(29);}}}
var FS={root:null,na:[],Va:{},streams:[],Ma:1,U:null,Ta:"/",Ga:!1,bb:!0,Cb:null,Ba:0,ib:{},h:class{name="ErrnoError";constructor(a){this.A=a}},pb:class{N={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.N.flags}set flags(a){this.N.flags=a}get position(){return this.N.position}set position(a){this.N.position=a}},ob:class{m={};o={};R=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Ma++;this.name=b;this.mode=c;this.qa=d;this.Z=
this.M=this.L=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Sb(){return FS.isDir(this.mode)}get Rb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=cg(e),FS.ma(d)){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=bg(e+"/"+a[f]);try{d=ug(d,a[f])}catch(h){if(44===h?.A&&g&&b.Wb)return{path:e};throw h;}!d.R||g&&!b.wa||(d=d.R.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=cg(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.ma(a))return a=a.mount.fb,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.ob(a,b,c,d);Bg(a);return a},ma(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},qb:4096,$a:a=>FS.streams[a],vb:{open(a){a.o=FS.Eb(a.node.qa).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ja:a=>a>>
8,Lc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Va[a]={o:b}},Eb:a=>FS.Va[a],syncfs(a,b){function c(g){FS.Ba--;return b(g)}function d(g){if(g){if(!d.Ab)return d.Ab=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ba++;1<FS.Ba&&v(`warning: ${FS.Ba} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Jg(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);
if(!d&&c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.R)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,Xb:b,fb:c,na:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.R=b,e.mount&&e.mount.na.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.R)throw new FS.h(28);a=a.node;var b=a.R,c=Jg(b);Object.keys(FS.U).forEach(d=>{for(d=FS.U[d];d;){var e=d.ja;c.includes(d.mount)&&vg(d);d=e}});a.R=null;a.mount.na.splice(a.mount.na.indexOf(b),1)},ha(a,b){return a.m.ha(a,
b)},aa(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=dg(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=Dg(d,a);if(e)throw new FS.h(e);if(!d.m.aa)throw new FS.h(63);return d.m.aa(d,a,b,c)},kb(a){return Kg(FS.lookupPath(a,{follow:!0}).node)},Oc(a){return Kg(a.node)},create(a,b=438){return FS.aa(a,b&4095|32768,0)},mkdir(a,b=511){return FS.aa(a,b&1023|16384,0)},Mc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.A)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.aa(a,b|8192,c)},symlink(a,b){if(!hg(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=dg(b);var d=Dg(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=cg(a),d=cg(b),e=dg(a),f=dg(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);
var k=ug(h,e);a=ig(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=ig(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var m=ug(g,f)}catch(p){}if(k!==m){b=FS.isDir(k.mode);if(e=Eg(h,e,b))throw new FS.h(e);if(e=m?Eg(g,f,b):Dg(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);if(k.R||m&&m.R)throw new FS.h(10);if(g!==h&&(e=zg(h,"w")))throw new FS.h(e);vg(k);try{h.m.rename(k,g,f),k.parent=g}catch(p){throw p;}finally{Bg(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=dg(a);var c=ug(b,a),
d=Eg(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.R)throw new FS.h(10);b.m.rmdir(b,a);vg(c)},ra(a){a=FS.lookupPath(a,{follow:!0}).node;return Fg(a.m.ra,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=dg(a);var c=ug(b,a),d=Eg(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.R)throw new FS.h(10);b.m.unlink(b,a);vg(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Fg(a.m.P,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Lg(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=U(a);Lg(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;Ig(null,a,{timestamp:Date.now(),Xa:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=U(a);Ig(a,a.node,{timestamp:Date.now(),Xa:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Mg(null,a,b)},ftruncate(a,b){a=U(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);Mg(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Fg(a.m.S,63)(a,{Z:b,M:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
a=FS.lookupPath(a,{follow:!(b&131072),Wb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.aa(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==Cg(g)||g&576)?31:zg(e,Cg(g)):44)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=Gg({node:d,path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,
oc:[],error:!1});e.o.open&&e.o.open(e);f&&FS.chmod(d,c&511);!l.logReadFiles||b&1||a in FS.ib||(FS.ib[a]=1);return e},close(a){if(null===a.$)throw new FS.h(8);a.Ea&&(a.Ea=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.$]=null}a.$=null},llseek(a,b,c){if(null===a.$)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.oc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);if(null===
a.$)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.$)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&a.flags&1024&&
FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ia(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ia)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ia(a,b,c,d,e)},ka(a,b,c,d,e){return a.o.ka?a.o.ka(a,b,c,d,e):0},Ha(a,b,c){if(!a.o.Ha)throw new FS.h(59);return a.o.Ha(a,b,c)},readFile(a,b={}){b.flags=b.flags||
0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=FS.open(a,b.flags);a=FS.stat(a).size;var e=new Uint8Array(a);FS.read(d,e,0,a,0);"utf8"===b.encoding?c=nf(e):"binary"===b.encoding&&(c=e);FS.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(kg(b)+1);b=lg(b,d,0,d.length);FS.write(a,d,0,b,void 0,c.ub)}else if(ArrayBuffer.isView(b))FS.write(a,
b,0,b.byteLength,void 0,c.ub);else throw Error("Unsupported data type");FS.close(a)},cwd:()=>FS.Ta,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);var b=zg(a.node,"x");if(b)throw new FS.h(b);FS.Ta=a.path},init(a,b,c){FS.Ga=!0;a??=l.stdin;b??=l.stdout;c??=l.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev",
"stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Fc(a,b){a=FS.analyzePath(a,b);return a.Ya?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={ma:!1,Ya:!1,error:0,name:null,path:null,object:null,Yb:!1,$b:null,Zb:null};try{c=FS.lookupPath(a,{parent:!0}),d.Yb=!0,d.$b=c.path,d.Zb=c.node,d.name=dg(a),c=FS.lookupPath(a,{follow:!b}),d.Ya=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,
d.ma="/"===c.path}catch(e){d.error=e.A}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=bg(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.A)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?bg(a+"/"+b):a);a=yg(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,
c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,b,c,d){a=eg("string"==typeof a?a:FS.getPath(a),b);b=yg(!!c,!!d);var e;(e=FS.createDevice).Ja??(e.Ja=64);e=FS.makedev(FS.createDevice.Ja++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var m=0,p=0;p<k;p++){try{var n=c()}catch(q){throw new FS.h(29);}if(void 0===n&&0===m)throw new FS.h(6);if(null===n||void 0===n)break;m++;g[h+p]=n}m&&(f.node.Z=Date.now());return m},write(f,g,h,k){for(var m=
0;m<k;m++)try{d(g[h+m])}catch(p){throw new FS.h(29);}k&&(f.node.M=f.node.L=Date.now());return m}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(n,q,t,u,y){n=n.node.u;if(y>=n.length)return 0;u=Math.min(n.length-y,u);if(n.slice)for(var C=0;C<u;C++)q[t+C]=n[y+C];else for(C=0;C<u;C++)q[t+C]=n.get(y+C);return u}class g{Fa=!1;N=[];la=void 0;eb=0;cb=0;get(n){if(!(n>this.length-1||0>n)){var q=n%this.jb;return this.la(n/this.jb|0)[q]}}nc(n){this.la=n}gb(){var n=new XMLHttpRequest;n.open("HEAD",
c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),t,u=(t=n.getResponseHeader("Accept-Ranges"))&&"bytes"===t;n=(t=n.getResponseHeader("Content-Encoding"))&&"gzip"===t;var y=1048576;u||(y=q);var C=this;C.nc(L=>{var M=L*y,I=(L+1)*y-1;I=Math.min(I,q-1);if("undefined"==typeof C.N[L]){var ka=C.N;if(M>I)throw Error("invalid range ("+M+", "+I+") or no bytes requested!");if(I>q-1)throw Error("only "+
q+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);q!==y&&O.setRequestHeader("Range","bytes="+M+"-"+I);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);M=void 0!==O.response?new Uint8Array(O.response||[]):mg(O.responseText||"");ka[L]=M}if("undefined"==typeof C.N[L])throw Error("doXHR failed!");
return C.N[L]});if(n||!q)y=q=1,y=q=this.la(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.eb=q;this.cb=y;this.Fa=!0}get length(){this.Fa||this.gb();return this.eb}get jb(){this.Fa||this.gb();return this.cb}}if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var m=Ng(a,b,d,e);h?m.u=h:k&&(m.u=
null,m.url=k);Object.defineProperties(m,{D:{get:function(){return this.u.length}}});var p={};Object.keys(m.o).forEach(n=>{var q=m.o[n];p[n]=(...t)=>{Og(m);return q(...t)}});p.read=(n,q,t,u,y)=>{Og(m);return f(n,q,t,u,y)};p.ia=(n,q,t)=>{Og(m);var u=tg(q);if(!u)throw new FS.h(48);f(n,w,u,q,t);return{s:u,ca:!0}};m.o=p;return m}},Pg=5;function Qg(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():U(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Rg(a,b){B[a>>2]=b.xb;B[a+4>>2]=b.mode;D[a+8>>2]=b.Vb;B[a+12>>2]=b.uid;B[a+16>>2]=b.Ib;B[a+20>>2]=b.qa;E[a+24>>3]=BigInt(b.size);B[a+32>>2]=4096;B[a+36>>2]=b.Ra;var c=b.Z.getTime(),d=b.M.getTime(),e=b.L.getTime();E[a+40>>3]=BigInt(Math.floor(c/1E3));D[a+48>>2]=c%1E3*1E6;E[a+56>>3]=BigInt(Math.floor(d/1E3));D[a+64>>2]=d%1E3*1E6;E[a+72>>3]=BigInt(Math.floor(e/1E3));D[a+80>>2]=e%1E3*1E6;E[a+88>>3]=BigInt(b.Nb);return 0}var Sg=void 0;
function wb(a){if(r)return P(3,1,a);try{var b=U(a);return Hg(b).$}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}wb.g="ii";function xb(a,b,c,d){if(r)return P(4,1,a,b,c,d);try{b=S(b);b=Qg(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&zg(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}xb.g="iipii";var Tg=()=>{var a=B[+Sg>>2];Sg+=4;return a};
function yb(a,b,c){if(r)return P(5,1,a,b,c);Sg=c;try{var d=U(a);switch(b){case 0:var e=Tg();if(0>e)break;for(;FS.streams[e];)e++;return Hg(d,e).$;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Tg(),d.flags|=e,0;case 12:return e=Tg(),z[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}yb.g="iiip";
function zb(a,b){if(r)return P(6,1,a,b);try{var c=U(a),d=c.node,e=c.o.P;a=e?c:d;e??=d.m.P;Fg(e,63);var f=e(a);return Rg(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.A}}zb.g="iip";function Ab(a,b){if(r)return P(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Ab.g="iij";
function Bb(a,b){if(r)return P(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=kg(c)+1;if(b<d)return-68;lg(c,x,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.A}}Bb.g="ipp";
function Cb(a,b,c){if(r)return P(9,1,a,b,c);Sg=c;try{var d=U(a);switch(b){case 21509:return d.B?0:-59;case 21505:if(!d.B)return-59;if(d.B.ba.Ob){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Tg();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.B?0:-59;case 21506:case 21507:case 21508:if(!d.B)return-59;if(d.B.ba.Pb)for(e=Tg(),a=[],f=0;32>f;f++)a.push(w[e+f+17]);
return 0;case 21519:if(!d.B)return-59;e=Tg();return B[e>>2]=0;case 21520:return d.B?-28:-59;case 21531:return e=Tg(),FS.Ha(d,b,e);case 21523:if(!d.B)return-59;d.B.ba.Qb&&(f=[24,80],e=Tg(),z[e>>1]=f[0],z[e+2>>1]=f[1]);return 0;case 21524:return d.B?0:-59;case 21515:return d.B?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.A}}Cb.g="iiip";
function Db(a,b){if(r)return P(10,1,a,b);try{return a=S(a),Rg(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Db.g="ipp";function Eb(a,b,c,d){if(r)return P(11,1,a,b,c,d);try{b=S(b);var e=d&256;b=Qg(a,b,d&4096);return Rg(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}Eb.g="iippi";
function Fb(a,b,c,d){if(r)return P(12,1,a,b,c,d);Sg=d;try{b=S(b);b=Qg(a,b);var e=d?Tg():0;return FS.open(b,c,e).$}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}Fb.g="iipip";function Gb(a,b,c){if(r)return P(13,1,a,b,c);try{for(var d=c=0;d<b;d++){var e=a+8*d,f=z[e+4>>1],g=32,h=FS.$a(B[e>>2]);h&&(g=Pg,h.o.bc&&(g=h.o.bc(h,-1)));(g&=f|24)&&c++;z[e+6>>1]=g}return c}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.A}}Gb.g="ipii";
function Hb(a){if(r)return P(14,1,a);try{return a=S(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.A}}Hb.g="ip";function Ib(a,b){if(r)return P(15,1,a,b);try{return a=S(a),Rg(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Ib.g="ipp";
function Jb(a,b,c){if(r)return P(16,1,a,b,c);try{return b=S(b),b=Qg(a,b),0===c?FS.unlink(b):512===c?FS.rmdir(b):Za("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.A}}Jb.g="iipi";var Kb=new WebAssembly.Global({value:"i32",mutable:!1},1),Lb=()=>Za("");Lb.g="v";
var Ug=a=>{var b=kg(a)+1,c=Je(b);lg(a,x,c,b);return c},Wg=a=>{var b=K();a=Ug(a);Vg(a,0);N(b)},Xg=(a,b)=>{var c=S(a+36),d=B[a+4>>2];c=bg(c);var e=!!(d&256),f=e?null:{};d={global:e,oa:!!(d&4096),G:b.G};if(b.G)return Lf(c,d,f,a);try{return Lf(c,d,f,a)}catch(g){return Wg(`Could not load dynamic lib: ${c}\n${g}`),0}},Mb=a=>Xg(a,{G:!1});Mb.g="pp";var Nb=(a,b)=>{a=sf[a].exports;b=Object.keys(a)[b];b=a[b];return Bf(b,b.g)};Nb.g="ppi";
var Ob=(a,b,c)=>{b=S(b);var d=sf[a];if(!d.exports.hasOwnProperty(b)||d.exports[b].Y)return Wg(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;a=Object.keys(d.exports).indexOf(b);b=d.exports[b];"function"==typeof b&&((d=zf(b))?b=d:(b=Bf(b,b.g),D[c>>2]=a));return b};Ob.g="pppp";var Yg={},Zg=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function $g(a){return this.fromWireType(D[a>>2])}
var ah={},bh={},ch={},dh=l.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},fh=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new dh("Mismatched type converter count");for(var k=0;k<a.length;++k)eh(a[k],h[k])}a.forEach(h=>ch[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,k)=>{bh.hasOwnProperty(h)?e[k]=bh[h]:(f.push(h),ah.hasOwnProperty(h)||(ah[h]=[]),ah[h].push(()=>{e[k]=bh[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Pb=a=>{var b=Yg[a];delete Yg[a];
var c=b.Oa,d=b.X,e=b.Za,f=e.map(g=>g.Hb).concat(e.map(g=>g.hc));fh([a],f,g=>{var h={};e.forEach((k,m)=>{var p=g[m],n=k.la,q=k.Gb,t=g[m+e.length],u=k.fc,y=k.ic;h[k.Bb]={read:C=>p.fromWireType(n(q,C)),write:(C,L)=>{var M=[];u(y,C,t.toWireType(M,L));Zg(M)},optional:g[m].optional}});return[{name:b.name,fromWireType:k=>{var m={},p;for(p in h)m[p]=h[p].read(k);d(k);return m},toWireType:(k,m)=>{for(var p in h)if(!(p in m||h[p].optional))throw new TypeError(`Missing field: "${p}"`);var n=c();for(p in h)h[p].write(n,
m[p]);null!==k&&k.push(d,n);return n},J:gh,readValueFromPointer:$g,I:d}]})};Pb.g="vp";var hh,V=a=>{for(var b="";x[a];)b+=hh[x[a++]];return b},W=l.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}},ih=a=>{throw new W(a);};
function jh(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(bh.hasOwnProperty(a)){if(c.Mb)return;throw new W(`Cannot register type '${d}' twice`);}bh[a]=b;delete ch[a];ah.hasOwnProperty(a)&&(b=ah[a],delete ah[a],b.forEach(e=>e()))}function eh(a,b,c={}){return jh(a,b,c)}
var Qb=(a,b,c,d,e)=>{b=V(b);if(d)a:switch(c){case 4:d=va;break a;case 8:d=xa;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?w:x;break a;case 2:d=e?z:A;break a;case 4:d=e?B:D;break a;case 8:d=e?E:wa;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);eh(a,{name:b,fromWireType:h=>{for(var k=D[h>>2],m=Array(k),p=h+Math.max(4,c)>>g,n=0;n<k;++n)m[n]=f[p+n];X(h);return m},toWireType:(h,k)=>{"number"==typeof k&&
(k=[k]);if(!Array.isArray(k))throw new W("Cannot pass non-array to C++ vector type "+b);k=Array.prototype.concat.apply([],k);var m=k.length,p=Math.max(4,c),n=kh(p+m*c);p=n+p>>g;D[n>>2]=m;f.set(k,p);null!==h&&h.push(X,n);return n},J:gh,readValueFromPointer:$g,I(h){X(h)}})};Qb.g="vpppii";
var lh=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},mh=(a,b,c)=>{switch(b){case 1:return c?d=>w[d]:d=>x[d];case 2:return c?d=>z[d>>1]:d=>A[d>>1];case 4:return c?d=>B[d>>2]:d=>D[d>>2];case 8:return c?d=>E[d>>3]:d=>wa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Rb=(a,b,c)=>{b=V(b);var d=b.includes("u");eh(a,{name:b,fromWireType:e=>e,toWireType:function(e,f){if("bigint"!=typeof f&&"number"!=typeof f)throw new TypeError(`Cannot convert "${lh(f)}" to ${this.name}`);
"number"==typeof f&&(f=BigInt(f));return f},J:gh,readValueFromPointer:mh(b,c,!d),I:null})};Rb.g="vpppjj";var gh=8,Sb=(a,b,c,d)=>{b=V(b);eh(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},J:gh,readValueFromPointer:function(e){return this.fromWireType(x[e])},I:null})};Sb.g="vppii";
var nh=a=>{throw new W(a.l.C.v.name+" instance already deleted");},oh=!1,ph=!1,qh=()=>{},rh=a=>{if(oh)return rh=b=>b.deleteLater(),rh(a);if("undefined"===typeof FinalizationRegistry)return rh=b=>b,a;ph=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.H?b.O.X(b.H):b.C.v.X(b.s))});rh=b=>{var c=b.l;c.H&&ph.register(b,{l:c},b);return b};qh=b=>{ph.unregister(b)};return rh(a)},sh=[],th=()=>{for(;sh.length;){var a=sh.pop();a.l.ga=!1;a["delete"]()}},uh;function vh(){}
var wh=(a,b)=>Object.defineProperty(b,"name",{value:a}),xh={},yh=(a,b,c)=>{if(void 0===a[b].F){var d=a[b];a[b]=function(...e){if(!a[b].F.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].F})!`);return a[b].F[e.length].apply(this,e)};a[b].F=[];a[b].F[d.ea]=d}},zh=(a,b,c)=>{if(l.hasOwnProperty(a)){if(void 0===c||void 0!==l[a].F&&void 0!==l[a].F[c])throw new W(`Cannot register public name '${a}' twice`);yh(l,a,a);if(l[a].F.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
l[a].F[c]=b}else l[a]=b,l[a].ea=c},Ah=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Bh(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.da=c;this.X=d;this.K=e;this.Db=f;this.ta=g;this.yb=h;this.cc=[]}var Ch=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.K}return a};
function Dh(a,b){if(null===b){if(this.Ia)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${lh(b)}" as a ${this.name}`);if(!b.l.s)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ch(b.l.s,b.l.C.v,this.v)}
function Eh(a,b){if(null===b){if(this.Ia)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Oa();null!==a&&a.push(this.X,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${lh(b)}" as a ${this.name}`);if(!b.l.s)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.C.ya)throw new W(`Cannot convert argument of type ${b.l.O?b.l.O.name:b.l.C.name} to parameter type ${this.name}`);c=Ch(b.l.s,b.l.C.v,this.v);if(this.za){if(void 0===b.l.H)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.kc){case 0:if(b.l.O===this)c=b.l.H;else throw new W(`Cannot convert argument of type ${b.l.O?b.l.O.name:b.l.C.name} to parameter type ${this.name}`);break;case 1:c=b.l.H;break;case 2:if(b.l.O===this)c=b.l.H;else{var d=b.clone();c=this.dc(c,Fh(()=>d["delete"]()));null!==a&&a.push(this.X,c)}break;default:throw new W("Unsupporting sharing policy");}}return c}
function Gh(a,b){if(null===b){if(this.Ia)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${lh(b)}" as a ${this.name}`);if(!b.l.s)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.C.ya)throw new W(`Cannot convert argument of type ${b.l.C.name} to parameter type ${this.name}`);return Ch(b.l.s,b.l.C.v,this.v)}
var Hh=(a,b,c)=>{if(b===c)return a;if(void 0===c.K)return null;a=Hh(a,b,c.K);return null===a?null:c.yb(a)},Ih={},Jh=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.K;)b=a.ta(b),a=a.K;return Ih[b]},Kh=(a,b)=>{if(!b.C||!b.s)throw new dh("makeClassHandle requires ptr and ptrType");if(!!b.O!==!!b.H)throw new dh("Both smartPtrType and smartPtr must be specified");b.count={value:1};return rh(Object.create(a,{l:{value:b,writable:!0}}))};
function Lh(a,b,c,d,e,f,g,h,k,m,p){this.name=a;this.v=b;this.Ia=c;this.ya=d;this.za=e;this.ac=f;this.kc=g;this.hb=h;this.Oa=k;this.dc=m;this.X=p;e||void 0!==b.K?this.toWireType=Eh:(this.toWireType=d?Dh:Gh,this.I=null)}var Mh=(a,b,c)=>{if(!l.hasOwnProperty(a))throw new dh("Replacing nonexistent public symbol");void 0!==l[a].F&&void 0!==c?l[a].F[c]=b:(l[a]=b,l[a].ea=c)},Y=(a,b)=>{a=V(a);var c=Q(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class Nh extends Error{}
var Ph=a=>{a=Oh(a);var b=V(a);X(a);return b},Qh=(a,b)=>{function c(f){e[f]||bh[f]||(ch[f]?ch[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Nh(`${a}: `+d.map(Ph).join([", "]));},Tb=(a,b,c,d,e,f,g,h,k,m,p,n,q)=>{p=V(p);f=Y(e,f);h&&=Y(g,h);m&&=Y(k,m);q=Y(n,q);var t=Ah(p);zh(t,function(){Qh(`Cannot construct ${p} due to unbound types`,[d])});fh([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var y=u.v;var C=y.da}else C=vh.prototype;u=wh(p,function(...ka){if(Object.getPrototypeOf(this)!==L)throw new W(`Use 'new' to construct ${p}`);
if(void 0===M.fa)throw new W(`${p} has no accessible constructor`);var O=M.fa[ka.length];if(void 0===O)throw new W(`Tried to invoke ctor of ${p} with invalid number of parameters (${ka.length}) - expected (${Object.keys(M.fa).toString()}) parameters instead!`);return O.apply(this,ka)});var L=Object.create(C,{constructor:{value:u}});u.prototype=L;var M=new Bh(p,u,L,q,y,f,h,m);if(M.K){var I;(I=M.K).ua??(I.ua=[]);M.K.ua.push(M)}y=new Lh(p,M,!0,!1,!1);I=new Lh(p+"*",M,!1,!1,!1);C=new Lh(p+" const*",M,
!1,!0,!1);xh[a]={pointerType:I,wb:C};Mh(t,u);return[y,I,C]})};Tb.g="vppppppppppppp";function Rh(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].I)return!0;return!1}
function Sh(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=Rh(b);c="void"!==b[0].name;d=[a,ih,d,e,Zg,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].I&&d.push(b[e].I);k=Rh(b);e=b.length-2;var m=[],p=["fn"];h&&p.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),p.push(`arg${g}Wired`);m=m.join(",");p=p.join(",");m=`return function (${m}) {\n`;k&&
(m+="var destructors = [];\n");var n=k?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");h&&(m+=`var thisWired = classParam['toWireType'](${n}, this);\n`);for(g=0;g<e;++g)m+=`var arg${g}Wired = argType${g}['toWireType'](${n}, arg${g});\n`,q.push(`argType${g}`);m+=(c||f?"var rv = ":"")+`invoker(${p});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].I&&(m+=`${f}_dtor(${f});\n`,
q.push(`${f}_dtor`));c&&(m+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [t,u]=[q,m+"}\n"];b=(new Function(...t,u))(...d);return wh(a,b)}
var Th=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},Uh=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ub=(a,b,c,d,e,f,g,h)=>{var k=Th(c,d);b=V(b);b=Uh(b);f=Y(e,f);fh([],[a],m=>{function p(){Qh(`Cannot call ${n} due to unbound types`,k)}m=m[0];var n=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=m.v.constructor;void 0===q[b]?(p.ea=c-1,q[b]=p):(yh(q,b,n),q[b].F[c-1]=p);fh([],k,t=>{t=Sh(n,[t[0],null].concat(t.slice(1)),null,f,g,h);void 0===
q[b].F?(t.ea=c-1,q[b]=t):q[b].F[c-1]=t;if(m.v.ua)for(const u of m.v.ua)u.constructor.hasOwnProperty(b)||(u.constructor[b]=t);return[]});return[]})};Ub.g="vppippppii";
var Vb=(a,b,c,d,e,f)=>{var g=Th(b,c);e=Y(d,e);fh([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.v.fa&&(h.v.fa=[]);if(void 0!==h.v.fa[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.v.fa[b-1]=()=>{Qh(`Cannot construct ${h.name} due to unbound types`,g)};fh([],g,m=>{m.splice(1,0,null);h.v.fa[b-1]=Sh(k,m,null,e,f);
return[]});return[]})};Vb.g="vpipppp";
var Wb=(a,b,c,d,e,f,g,h,k)=>{var m=Th(c,d);b=V(b);b=Uh(b);f=Y(e,f);fh([],[a],p=>{function n(){Qh(`Cannot call ${q} due to unbound types`,m)}p=p[0];var q=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&p.v.cc.push(b);var t=p.v.da,u=t[b];void 0===u||void 0===u.F&&u.className!==p.name&&u.ea===c-2?(n.ea=c-2,n.className=p.name,t[b]=n):(yh(t,b,q),t[b].F[c-2]=n);fh([],m,y=>{y=Sh(q,y,p,f,g,k);void 0===t[b].F?(y.ea=c-2,t[b]=y):t[b].F[c-2]=y;return[]});return[]})};Wb.g="vppippppiii";
var Vh=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.v.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.s)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return Ch(a.l.s,a.l.C.v,b.v)},Xb=(a,b,c,d,e,f,g,h,k,m)=>{b=V(b);e=Y(d,e);fh([],[a],p=>{p=p[0];var n=`${p.name}.${b}`,q={get(){Qh(`Cannot access ${n} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};q.set=
k?()=>Qh(`Cannot access ${n} due to unbound types`,[c,g]):()=>{throw new W(n+" is a read-only property");};Object.defineProperty(p.v.da,b,q);fh([],k?[c,g]:[c],t=>{var u=t[0],y={get(){var L=Vh(this,p,n+" getter");return u.fromWireType(e(f,L))},enumerable:!0};if(k){k=Y(h,k);var C=t[1];y.set=function(L){var M=Vh(this,p,n+" setter"),I=[];k(m,M,C.toWireType(I,L));Zg(I)}}Object.defineProperty(p.v.da,b,y);return[]});return[]})};Xb.g="vpppppppppp";
var Wh=[],Xh=[],xc=a=>{9<a&&0===--Xh[a+1]&&(Xh[a]=void 0,Wh.push(a))};xc.g="vp";var Z=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Xh[a]},Fh=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Wh.pop()||Xh.length;Xh[b]=a;Xh[b+1]=1;return b}},Yh={name:"emscripten::val",fromWireType:a=>{var b=Z(a);xc(a);return b},toWireType:(a,b)=>Fh(b),J:gh,readValueFromPointer:$g,I:null},Yb=a=>eh(a,Yh);Yb.g="vp";
var Zh=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType(w[d])}:function(d){return this.fromWireType(x[d])};case 2:return c?function(d){return this.fromWireType(z[d>>1])}:function(d){return this.fromWireType(A[d>>1])};case 4:return c?function(d){return this.fromWireType(B[d>>2])}:function(d){return this.fromWireType(D[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Zb=(a,b,c,d)=>{function e(){}b=V(b);e.values={};eh(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},
toWireType:(f,g)=>g.value,J:gh,readValueFromPointer:Zh(b,c,d),I:null});zh(b,e)};Zb.g="vpppi";var $h=(a,b)=>{var c=bh[a];if(void 0===c)throw a=`${b} has unknown type ${Ph(a)}`,new W(a);return c},$b=(a,b,c)=>{var d=$h(a,"enum");b=V(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:wh(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d};$b.g="vppi";
var ci=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(va[c>>2])};case 8:return function(c){return this.fromWireType(xa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ac=(a,b,c)=>{b=V(b);eh(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,J:gh,readValueFromPointer:ci(b,c),I:null})};ac.g="vppp";
var bc=(a,b,c,d,e,f,g)=>{var h=Th(b,c);a=V(a);a=Uh(a);e=Y(d,e);zh(a,function(){Qh(`Cannot call ${a} due to unbound types`,h)},b-1);fh([],h,k=>{Mh(a,Sh(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};bc.g="vpippppii";var cc=(a,b,c,d,e)=>{b=V(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var f=32-8*c;e=h=>h<<f>>>f}var g=b.includes("unsigned")?function(h,k){return k>>>0}:function(h,k){return k};eh(a,{name:b,fromWireType:e,toWireType:g,J:gh,readValueFromPointer:mh(b,c,0!==d),I:null})};
cc.g="vpppii";var dc=(a,b,c)=>{function d(f){return new e(w.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);eh(a,{name:c,fromWireType:d,J:gh,readValueFromPointer:d},{Mb:!0})};dc.g="vpip";
var ec=(a,b)=>{b=V(b);eh(a,{name:b,fromWireType:function(c){for(var d=D[c>>2],e=c+4,f,g=e,h=0;h<=d;++h){var k=e+h;if(h==d||0==x[k])g=S(g,k-g),void 0===f?f=g:(f+=String.fromCharCode(0),f+=g),g=k+1}X(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?kg(d):d.length;var g=kh(4+f+1),h=g+4;D[g>>2]=f;e?lg(d,x,h,f+1):x.set(d,h);null!==
c&&c.push(X,g);return g},J:gh,readValueFromPointer:$g,I(c){X(c)}})};ec.g="vpp";
var di=new TextDecoder("utf-16le"),ei=(a,b)=>{var c=a>>1;for(b=c+b/2;!(c>=b)&&A[c];)++c;return di.decode(x.slice(a,c<<1))},fi=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},gi=a=>2*a.length,hi=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=B[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ii=(a,b,c)=>{c??=2147483647;
if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},ji=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},fc=(a,b,c)=>{c=V(c);if(2===b){var d=ei;var e=fi;var f=gi;var g=h=>A[h>>1]}else 4===b&&(d=hi,e=ii,f=ji,g=h=>D[h>>2]);eh(a,{name:c,fromWireType:h=>{for(var k=D[h>>2],m,p=h+4,n=0;n<=k;++n){var q=
h+4+n*b;if(n==k||0==g(q))p=d(p,q-p),void 0===m?m=p:(m+=String.fromCharCode(0),m+=p),p=q+b}X(h);return m},toWireType:(h,k)=>{if("string"!=typeof k)throw new W(`Cannot pass non-string to C++ string type ${c}`);var m=f(k),p=kh(4+m+b);D[p>>2]=m/b;e(k,p+4,m+b);null!==h&&h.push(X,p);return p},J:gh,readValueFromPointer:$g,I(h){X(h)}})};fc.g="vppp";var gc=(a,b,c,d,e,f)=>{Yg[a]={name:V(b),Oa:Y(c,d),X:Y(e,f),Za:[]}};gc.g="vpppppp";
var hc=(a,b,c,d,e,f,g,h,k,m)=>{Yg[a].Za.push({Bb:V(b),Hb:c,la:Y(d,e),Gb:f,hc:g,fc:Y(h,k),ic:m})};hc.g="vpppppppppp";var ic=(a,b)=>{b=V(b);eh(a,{Tb:!0,name:b,J:0,fromWireType:()=>{},toWireType:()=>{}})};ic.g="vpp";var jc=(a,b,c,d)=>{function e(h){var k=S(a+36);Wg(`'Could not load dynamic lib: ${k}\n${h}`);--J;Qe(()=>Q(c)(a,d))}function f(){--J;Qe(()=>Q(b)(a,d))}J+=1;var g=Xg(a,{G:!0});g?g.then(f,e):e()};jc.g="vpppp";var kc=()=>{for(const a of Object.keys(te)){const b=Number(a);ue.has(b)||ki(b)}};
kc.g="v";function li(a){var b=mi,c=b.N.pop()||b.ca.length;b.ca[c]=a;return c}function ni(a){var b=mi;b.ca[a]=void 0;b.N.push(a)}class oi{ca=[void 0];N=[];get(a){return this.ca[a]}has(a){return void 0!==this.ca[a]}}
var mi=new oi,pi=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=li(a);return a},lc=(a,b,c)=>{const d=[];0===Object.keys(ve).length||Za();var e=pi();d.push(e.promise);qi(e.id);for(const f of Object.keys(te)){const g=Number(f);g===a||ue.has(g)||(e=pi(),ri(g,e.id),ve[g]=e,d.push(e.promise))}Promise.all(d).then(()=>{ve={};Q(b)(c)})};lc.g="vppp";
function mc(){var a=kh(4*(pa.length+1)),b=a;pa.forEach(c=>{var d=D,e=b>>2,f=kg(c)+1,g=kh(f);g&&lg(c,x,g,f);d[e]=g;b+=4});D[b>>2]=0;return a}mc.g="p";var nc=a=>{Ja(a,!ea,1,!da,262144,!1);Ka()};nc.g="vp";var La=a=>{"function"===typeof Atomics.pc&&(Atomics.pc(B,a>>2,a).value.then(Oa),Atomics.store(B,a+128>>2,1))};La.g="vp";var Oa=()=>{var a=Ie();a&&(La(a),Qe(si))},oc=(a,b)=>{a==b?setTimeout(Oa):r?postMessage({Ca:a,T:"checkMailbox"}):(a=te[a])&&a.postMessage({T:"checkMailbox"})};oc.g="vpp";
var ti=[],pc=(a,b,c,d,e)=>{d/=2;ti.length=d;c=e>>3;for(e=0;e<d;e++)ti[e]=E[c+2*e]?E[c+2*e+1]:xa[c+2*e+1];return(b?If[b]:ui[a])(...ti)};pc.g="dippip";var qc=()=>{Le=!1;J=0};qc.g="v";var rc=a=>{r?postMessage({T:"cleanupThread",Qa:a}):ze(a)};rc.g="vp";var sc=a=>{r?postMessage({T:"markAsFinished",Qa:a}):(ue.add(a),a in ve&&ve[a].resolve())};sc.g="vp";var tc=()=>{};tc.g="vp";var uc=()=>{throw new Ba;};uc.g="v";
var vi=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(D[b>>2]=Fh(d));return a},vc=(a,b,c)=>{a=Z(a);b=$h(b,"emval::as");return vi(b,c,a)};vc.g="dppp";var wi=[],wc=(a,b,c,d)=>{a=wi[a];b=Z(b);return a(null,b,c,d)};wc.g="dpppp";var xi={},yi=a=>{var b=xi[a];return void 0===b?V(a):b},zi=()=>"object"==typeof globalThis?globalThis:Function("return this")(),yc=a=>{if(0===a)return Fh(zi());a=yi(a);return Fh(zi()[a])};yc.g="pp";
var Ai=a=>{var b=wi.length;wi.push(a);return b},Bi=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=$h(D[b+4*d>>2],`parameter ${d}`);return c},zc=(a,b,c)=>{b=Bi(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,g=[];0===c&&g.push("obj");for(var h=["retType"],k=[d],m=0;m<a;++m)g.push(`arg${m}`),h.push(`argType${m}`),k.push(b[m]),e+=`  var arg${m} = argType${m}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[m].J;e+=`  var rv = ${1===c?"new func":"func.call"}(${g.join(", ")});\n`;
d.Tb||(h.push("emval_returnValue"),k.push(vi),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");a=(new Function(...h,e+"};\n"))(...k);c=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return Ai(wh(c,a))};zc.g="pipi";var Ac=a=>{a=yi(a);return Fh(l[a])};Ac.g="pp";var Bc=(a,b)=>{a=Z(a);b=Z(b);return Fh(a[b])};Bc.g="ppp";var Cc=a=>{9<a&&(Xh[a+1]+=1)};Cc.g="vp";var Dc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};Dc.g="ipp";var Ec=a=>{a=Z(a);return"number"==typeof a};Ec.g="ip";
var Fc=a=>{a=Z(a);return"string"==typeof a};Fc.g="ip";var Gc=a=>Fh(yi(a));Gc.g="pp";var Hc=a=>{var b=Z(a);Zg(b);xc(a)};Hc.g="vp";var Ic=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};Ic.g="vppp";var Jc=(a,b)=>{a=$h(a,"_emval_take_value");a=a.readValueFromPointer(b);return Fh(a)};Jc.g="ppp";var Kc=a=>{a=Z(a);return Fh(typeof a)};Kc.g="pp";
function Lc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getUTCSeconds();B[b+4>>2]=a.getUTCMinutes();B[b+8>>2]=a.getUTCHours();B[b+12>>2]=a.getUTCDate();B[b+16>>2]=a.getUTCMonth();B[b+20>>2]=a.getUTCFullYear()-1900;B[b+24>>2]=a.getUTCDay();B[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}Lc.g="vjp";var Ci=[0,31,60,91,121,152,182,213,244,274,305,335],Di=[0,31,59,90,120,151,181,212,243,273,304,334];
function Mc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=a.getFullYear();B[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Di:Ci)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}Mc.g="vjp";function Nc(a,b,c,d,e,f,g){if(r)return P(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{if(isNaN(e))return 61;var h=U(d),k=FS.ia(h,a,e,b,c),m=k.s;B[f>>2]=k.ca;D[g>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return-p.A}}Nc.g="ipiiijpp";
function Oc(a,b,c,d,e,f){if(r)return P(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=U(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.ka(g,x.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.A}}Oc.g="ippiiij";
var Pc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(lg(a,x,c,17),lg(b,x,d,17)):(lg(a,x,d,17),lg(b,x,c,17))};Pc.g="vpppp";var Wc=()=>performance.timeOrigin+performance.now();Wc.g="d";var Sc=()=>Date.now();Sc.g="d";var Ei=1;
function Qc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Ei)a=performance.timeOrigin+performance.now();else return 52;E[c>>3]=BigInt(Math.round(1E6*a));return 0}Qc.g="iijp";var Rc=()=>{};Rc.g="v";var Tc=a=>v(S(a));Tc.g="vp";var Uc=()=>{J+=1;throw"unwind";};Uc.g="v";var Vc=()=>x.length;Vc.g="p";var Xc=()=>navigator.hardwareConcurrency;Xc.g="i";var Yc=a=>{ni(a)};Yc.g="vp";
var Zc=(a,b,c)=>{a=mi.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(mi.get(c).promise);break;case 2:a.resolve(mi.get(c).promise);ni(c);break;case 3:a.reject(c)}};Zc.g="vpip";var $c=()=>!1;$c.g="ip";
var Fi={},Hi=()=>{if(!Gi){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ha||"./this.program"},b;for(b in Fi)void 0===Fi[b]?delete a[b]:a[b]=Fi[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Gi=c}return Gi},Gi;function ad(a,b){if(r)return P(19,1,a,b);var c=0,d=0,e;for(e of Hi()){var f=b+c;D[a+d>>2]=f;c+=lg(e,x,f,Infinity)+1;d+=4}return 0}ad.g="ipp";
function bd(a,b){if(r)return P(20,1,a,b);var c=Hi();D[a>>2]=c.length;a=0;for(var d of c)a+=kg(d)+1;D[b>>2]=a;return 0}bd.g="ipp";function dd(a){if(r)return P(21,1,a);try{var b=U(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.A}}dd.g="ii";
function ed(a,b){if(r)return P(22,1,a,b);try{var c=U(a),d=c.B?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;w[b]=d;z[b+2>>1]=0;E[b+8>>3]=BigInt(0);E[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.A}}ed.g="iip";
function fd(a,b,c,d){if(r)return P(23,1,a,b,c,d);try{a:{var e=U(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],k=D[a+4>>2];a+=8;var m=FS.read(e,w,h,k,f);if(0>m){var p=-1;break a}b+=m;if(m<k)break;"undefined"!=typeof f&&(f+=m)}p=b}D[d>>2]=p;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return n.A}}fd.g="iippp";
function gd(a,b,c,d){if(r)return P(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=U(a);FS.llseek(e,b,c);E[d>>3]=BigInt(e.position);e.Ea&&0===b&&0===c&&(e.Ea=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.A}}gd.g="iijip";
function hd(a,b,c,d){if(r)return P(25,1,a,b,c,d);try{a:{var e=U(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],k=D[a+4>>2];a+=8;var m=FS.write(e,w,h,k,f);if(0>m){var p=-1;break a}b+=m;if(m<k)break;"undefined"!=typeof f&&(f+=m)}p=b}D[d>>2]=p;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return n.A}}hd.g="iippp";function kd(...a){return H.heif_error_success(...a)}kd.Y=!0;function ld(...a){return H.heif_image_get_bits_per_pixel_range(...a)}ld.Y=!0;
function md(...a){return H.heif_image_get_chroma_format(...a)}md.Y=!0;function nd(...a){return H.heif_image_get_nclx_color_profile(...a)}nd.Y=!0;function od(...a){return H.heif_image_get_plane_readonly(...a)}od.Y=!0;function pd(...a){return H.heif_image_release(...a)}pd.Y=!0;function qd(...a){return H.heif_nclx_color_profile_free(...a)}qd.Y=!0;var me=a=>a;me.g="vp";function oe(a,b){try{return gg(x.subarray(a,a+b)),0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.A}}
oe.g="ipp";var Ii=FS.createPath,Ji=FS.createLazyFile,Ki=FS.createDevice,Da=a=>{var b=K(),c=Je(4),d=Je(4);Li(a,c,d);a=D[c>>2];d=D[d>>2];c=S(a);X(a);if(d){var e=S(d);X(d)}N(b);return[c,e]};
l.requestFullscreen=function(a,b){function c(){Ue=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=cf,af&&d.requestPointerLock(),Ue=!0,bf?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=D[SDL.screen>>2]|8388608),ff(l.canvas),ef()):ff(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),bf?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=
D[SDL.screen>>2]&-8388609),ff(l.canvas),ef()):ff(d));l.onFullScreen?.(Ue);l.onFullscreen?.(Ue)}af=a;bf=b;"undefined"==typeof af&&(af=!0);"undefined"==typeof bf&&(bf=!1);var d=l.canvas;$e||($e=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};l.setCanvasSize=function(a,b,c){ff(l.canvas,a,b);c||ef()};l.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
l.createContext=function(a,b,c,d){if(b&&l.ctx&&a==l.canvas)return l.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Jc:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof GL&&(e=GL.Cc(a,f)))var h=GL.getContext(e).tc}else h=a.getContext("2d");if(!h)return null;c&&(l.ctx=h,b&&GL.Kc(e),We.forEach(k=>k()),Xe());return h};r||Fe();
(()=>{var a={promiseChainEnd:Promise.resolve(),canHandle:b=>!l.noWasmDecoding&&b.endsWith(".so"),handle:(b,c,d,e)=>{a.promiseChainEnd=a.promiseChainEnd.then(()=>Mf(b,{G:!0,oa:!0},c,{})).then(f=>{Te[c]=f;d(b)},f=>{v(`failed to instantiate wasm: ${c}: ${f}`);e()})}};Se.push(a)})();FS.createPreloadedFile=xg;FS.U=Array(4096);FS.mount(T,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));og(FS.makedev(5,0),qg);og(FS.makedev(6,0),rg);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(gg(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:T.o.llseek};b.m={ha(c,d){c=+d;var e=U(c);c={parent:null,mount:{fb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},ra(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Cb={MEMFS:T};l.FS_createPath=FS.createPath;l.FS_createDataFile=FS.createDataFile;
l.FS_createPreloadedFile=FS.createPreloadedFile;l.FS_unlink=FS.unlink;l.FS_createLazyFile=FS.createLazyFile;l.FS_createDevice=FS.createDevice;T.Wa=new FS.h(44);T.Wa.stack="<generic error, no stack>";for(var Mi=Array(256),Ni=0;256>Ni;++Ni)Mi[Ni]=String.fromCharCode(Ni);hh=Mi;
(()=>{let a=vh.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof vh&&c instanceof vh))return!1;var d=this.l.C.v,e=this.l.s;c.l=c.l;var f=c.l.C.v;for(c=c.l.s;d.K;)e=d.ta(e),d=d.K;for(;f.K;)c=f.ta(c),f=f.K;return d===f&&e===c},clone:function(){this.l.s||nh(this);if(this.l.pa)return this.l.count.value+=1,this;var c=rh,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ga:g.ga,pa:g.pa,s:g.s,C:g.C,H:g.H,O:g.O}}}));c.l.count.value+=1;c.l.ga=
!1;return c},["delete"](){this.l.s||nh(this);if(this.l.ga&&!this.l.pa)throw new W("Object already scheduled for deletion");qh(this);var c=this.l;--c.count.value;0===c.count.value&&(c.H?c.O.X(c.H):c.C.v.X(c.s));this.l.pa||(this.l.H=void 0,this.l.s=void 0)},isDeleted:function(){return!this.l.s},deleteLater:function(){this.l.s||nh(this);if(this.l.ga&&!this.l.pa)throw new W("Object already scheduled for deletion");sh.push(this);1===sh.length&&uh&&uh(th);this.l.ga=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(Lh.prototype,{Fb(a){this.hb&&(a=this.hb(a));return a},Ua(a){this.X?.(a)},J:gh,readValueFromPointer:$g,fromWireType:function(a){function b(){return this.za?Kh(this.v.da,{C:this.ac,s:c,O:this,H:a}):Kh(this.v.da,{C:this,s:a})}var c=this.Fb(a);if(!c)return this.Ua(a),null;var d=Jh(this.v,c);if(void 0!==d){if(0===d.l.count.value)return d.l.s=c,d.l.H=a,d.clone();d=d.clone();this.Ua(a);return d}d=this.v.Db(c);d=xh[d];if(!d)return b.call(this);d=this.ya?d.wb:d.pointerType;var e=Hh(c,this.v,
d.v);return null===e?b.call(this):this.za?Kh(d.v.da,{C:d,s:e,O:this,H:a}):Kh(d.v.da,{C:d,s:e})}});Xh.push(0,1,void 0,1,null,1,!0,1,!1,1);l.count_emval_handles=()=>Xh.length/2-5-Wh.length;Ae.push(()=>{Fi.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;Fi.VIPS_CONCURRENCY=1});
Ua.push(()=>{const a=Object.getOwnPropertyDescriptor(l.SourceCustom.prototype,"onRead");Object.defineProperty(l.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>Fh(c(d)))}});const b=Object.getOwnPropertyDescriptor(l.TargetCustom.prototype,"onWrite");Object.defineProperty(l.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(vh.prototype,{preventAutoDelete:function(){const a=sh.indexOf(this);-1<a&&sh.splice(a,1);this.l.ga=!1;return this}});
if(!r){if(l.wasmMemory)ra=l.wasmMemory;else{var Oi=l.INITIAL_MEMORY||1073741824;ra=new WebAssembly.Memory({initial:Oi/65536,maximum:Oi/65536,shared:!0})}Ha()}l.preloadPlugins&&(Se=l.preloadPlugins);l.noExitRuntime&&(Le=l.noExitRuntime);l.print&&(oa=l.print);l.printErr&&(v=l.printErr);l.dynamicLibraries&&(pa=l.dynamicLibraries);l.wasmBinary&&(qa=l.wasmBinary);l.arguments&&(fa=l.arguments);l.thisProgram&&(ha=l.thisProgram);l.addRunDependency=Xa;l.removeRunDependency=Ya;l.ENV=Fi;l.addFunction=Bf;
l.FS_createPreloadedFile=xg;l.FS_unlink=a=>FS.unlink(a);l.FS_createPath=Ii;l.FS_createDevice=Ki;l.FS=FS;l.FS_createDataFile=(a,b,c,d,e,f)=>{FS.createDataFile(a,b,c,d,e,f)};l.FS_createLazyFile=Ji;l.setAutoDeleteLater=a=>{oh=a};l.deletionQueue=sh;l.setDelayFunction=a=>{uh=a;sh.length&&uh&&uh(th)};l.incrementExceptionRefcount=a=>Uf(a);l.decrementExceptionRefcount=a=>Xf(a);l.getExceptionMessage=a=>Da(a);var ui=[ne,Me,$f,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Nc,Oc,ad,bd,dd,ed,fd,gd,hd],If={};
function Pi(a){for(var b=A[a+6>>1];13===b&&!(16<D[a>>2]);){var c=D[a+8>>2],d=D[c>>2];if(0===d){b=0;break}else if(0===D[(c>>2)+1])a=d,b=A[d+6>>1];else break}return[a,b]}
function jd(a,b,c,d){var e=D[(a>>2)+1],f=D[(a>>2)+6],g=D[(a>>2)+2];a=Pi(D[(a>>2)+3])[1];var h=K(),k=h,m=[],p=0;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),p=1;for(var n=0;n<f;n++){var q=D[(d>>2)+n],t=Pi(D[(g>>2)+n]),u=t[0];t=t[1];switch(t){case 1:case 10:case 9:case 14:m.push(D[q>>2]);break;case 2:m.push(va[q>>2]);break;case 3:m.push(xa[q>>3]);break;case 5:m.push(x[q]);break;case 6:m.push(w[q]);break;case 7:m.push(A[q>>
1]);break;case 8:m.push(z[q>>1]);break;case 11:case 12:m.push(wa[q>>3]);break;case 4:m.push(wa[q>>3]);m.push(wa[(q>>3)+1]);break;case 13:t=D[u>>2];u=A[u+4>>1];k-=t;k&=~(u-1);w.subarray(k,k+t).set(w.subarray(q,q+t));m.push(k);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+t);}}if(f!=e){var y=[];for(n=e-1;n>=f;n--)switch(q=D[(d>>2)+n],t=Pi(D[(g>>2)+n]),u=t[0],t=t[1],t){case 5:case 6:--k;k&=-1;x[k]=x[q];break;case 7:case 8:k-=2;k&=-2;A[k>>1]=A[q>>1];break;
case 1:case 9:case 10:case 14:case 2:k-=4;k&=-4;D[k>>2]=D[q>>2];break;case 3:case 11:case 12:k-=8;k&=-8;D[k>>2]=D[q>>2];D[(k>>2)+1]=D[(q>>2)+1];break;case 4:k-=16;k&=-8;D[k>>2]=D[q>>2];D[(k>>2)+1]=D[(q>>2)+1];D[(k>>2)+2]=D[(q>>2)+2];D[(k>>2)+3]=D[(q>>2)+3];break;case 13:k-=4;k&=-4;y.push([k,q,D[u>>2],A[u+4>>1]]);break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+t);}m.push(k);for(n=0;n<y.length;n++)e=y[n],d=e[0],q=e[1],t=e[2],u=e[3],k-=t,k&=~(u-1),w.subarray(k,
k+t).set(w.subarray(q,q+t)),D[d>>2]=k}N(k);Je(0);null;b=Q(b).apply(null,m);N(h);if(!p)switch(a){case 0:break;case 1:case 9:case 10:case 14:D[c>>2]=b;break;case 2:va[c>>2]=b;break;case 3:xa[c>>3]=b;break;case 5:case 6:x[c+0]=b;break;case 7:case 8:A[c>>1]=b;break;case 11:case 12:wa[c>>3]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}jd.g="viiii";
var H,G=await (async function(){function a(d,e){G=d.exports;G=Cf(G,1024);var f=of(e);Of(G);tf("__main__",0,H);Qf();Kf(G._emscripten_tls_init,d.exports,f);Ra.push(G.__wasm_apply_data_relocs);sa=e;Ya("wasm-instantiate");return G}Xa("wasm-instantiate");var b=db();if(l.instantiateWasm)return new Promise(d=>{l.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(r)return new Promise(d=>{Fa=e=>{var f=new WebAssembly.Instance(e,db());d(a(f,e))}});$a??=la("vips.wasm");try{var c=await cb(b);return a(c.instance,
c.module)}catch(d){return ba(d),Promise.reject(d)}}()),Oh=a=>(Oh=G.__getTypeName)(a),Ma=()=>(Ma=G._embind_initialize_bindings)(),Ie=()=>(Ie=G.pthread_self)(),kh=a=>(kh=G.malloc)(a);l._main=(a,b)=>(l._main=G.main)(a,b);var X=a=>(X=G.free)(a),Oe=a=>(Oe=G.fflush)(a),vf=(a,b)=>(vf=G.calloc)(a,b);l._emscripten_builtin_free=a=>(l._emscripten_builtin_free=G.emscripten_builtin_free)(a);var sg=(a,b)=>(sg=G.emscripten_builtin_memalign)(a,b);l._emscripten_builtin_malloc=a=>(l._emscripten_builtin_malloc=G.emscripten_builtin_malloc)(a);
var Ne=()=>(Ne=G.__funcs_on_exit)();l.___libc_calloc=(a,b)=>(l.___libc_calloc=G.__libc_calloc)(a,b);l.___libc_free=a=>(l.___libc_free=G.__libc_free)(a);l.___libc_malloc=a=>(l.___libc_malloc=G.__libc_malloc)(a);
var Vg=(a,b)=>(Vg=G.__dl_seterr)(a,b),qi=a=>(qi=G._emscripten_dlsync_self_async)(a),qf=()=>(qf=G._emscripten_dlsync_self)(),ri=(a,b)=>(ri=G._emscripten_proxy_dlsync_async)(a,b),ki=a=>(ki=G._emscripten_proxy_dlsync)(a),Ja=(a,b,c,d,e,f)=>(Ja=G._emscripten_thread_init)(a,b,c,d,e,f),Qa=()=>(Qa=G._emscripten_thread_crashed)(),Ke=(a,b,c,d,e)=>(Ke=G._emscripten_run_on_main_thread_js)(a,b,c,d,e),ye=a=>(ye=G._emscripten_thread_free_data)(a),Pe=a=>(Pe=G._emscripten_thread_exit)(a);
l._strndup=(a,b)=>(l._strndup=G.strndup)(a,b);var si=()=>(si=G._emscripten_check_mailbox)();l.__ZdaPvm=(a,b)=>(l.__ZdaPvm=G._ZdaPvm)(a,b);l.__Znaj=a=>(l.__Znaj=G._Znaj)(a);l.__ZnajSt11align_val_t=(a,b)=>(l.__ZnajSt11align_val_t=G._ZnajSt11align_val_t)(a,b);l.__Znwj=a=>(l.__Znwj=G._Znwj)(a);l.__ZnwjSt11align_val_t=(a,b)=>(l.__ZnwjSt11align_val_t=G._ZnwjSt11align_val_t)(a,b);l.___libc_realloc=(a,b)=>(l.___libc_realloc=G.__libc_realloc)(a,b);
l._emscripten_builtin_calloc=(a,b)=>(l._emscripten_builtin_calloc=G.emscripten_builtin_calloc)(a,b);l._emscripten_builtin_realloc=(a,b)=>(l._emscripten_builtin_realloc=G.emscripten_builtin_realloc)(a,b);l._malloc_size=a=>(l._malloc_size=G.malloc_size)(a);l._malloc_usable_size=a=>(l._malloc_usable_size=G.malloc_usable_size)(a);l._reallocf=(a,b)=>(l._reallocf=G.reallocf)(a,b);
var R=(a,b)=>(R=G.setThrew)(a,b),Yf=a=>(Yf=G._emscripten_tempret_set)(a),lf=(a,b)=>(lf=G.emscripten_stack_set_limits)(a,b),N=a=>(N=G._emscripten_stack_restore)(a),Je=a=>(Je=G._emscripten_stack_alloc)(a),K=()=>(K=G.emscripten_stack_get_current)(),Uf=a=>(Uf=G.__cxa_increment_exception_refcount)(a),Xf=a=>(Xf=G.__cxa_decrement_exception_refcount)(a),Li=(a,b,c)=>(Li=G.__get_exception_message)(a,b,c),Zf=(a,b,c)=>(Zf=G.__cxa_can_catch)(a,b,c),Vf=a=>(Vf=G.__cxa_get_exception_ptr)(a);l.___THREW__=1200;
l.__ZTISt12length_error=1431408;l.__ZTVSt12length_error=1431388;l.__ZTVN10__cxxabiv120__si_class_type_infoE=1431080;l.__ZTVN10__cxxabiv117__class_type_infoE=1431040;l.__ZTISt20bad_array_new_length=1431280;l.___threwValue=1204;l._stdout=1424336;l._stderr=1424184;l._g_mem_gc_friendly=3352204;l._g_utf8_skip=1367380;l.__ZTVNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1434964;l.__ZTTNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1435380;
l.__ZTTNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1435612;l.__ZTVNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1435320;l.__ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1435572;l.__ZNSt3__24coutE=3419248;l.__ZNSt3__24cerrE=3419424;l.__ZNSt3__25ctypeIcE2idE=3416452;l.__ZTVNSt3__212bad_weak_ptrE=1431536;l.__ZTINSt3__212bad_weak_ptrE=1431556;l.__ZTINSt3__219__shared_weak_countE=1431596;l.__ZTISt9bad_alloc=1431292;
l.__ZSt7nothrow=944276;l.__ZTISt12out_of_range=1431440;l.__ZTVSt12out_of_range=1431420;l.__ZTVN10__cxxabiv121__vmi_class_type_infoE=1431132;function Nd(a,b){var c=K();try{Q(a)(b)}catch(d){N(c);if(!(d instanceof F))throw d;R(1,0)}}function Vd(a,b,c,d){var e=K();try{Q(a)(b,c,d)}catch(f){N(e);if(!(f instanceof F))throw f;R(1,0)}}function yd(a,b,c){var d=K();try{return Q(a)(b,c)}catch(e){N(d);if(!(e instanceof F))throw e;R(1,0)}}
function xd(a,b){var c=K();try{return Q(a)(b)}catch(d){N(c);if(!(d instanceof F))throw d;R(1,0)}}function wd(a){var b=K();try{return Q(a)()}catch(c){N(b);if(!(c instanceof F))throw c;R(1,0)}}function Md(a){var b=K();try{Q(a)()}catch(c){N(b);if(!(c instanceof F))throw c;R(1,0)}}function be(a,b,c,d,e){var f=K();try{Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}function td(a,b,c,d){var e=K();try{return Q(a)(b,c,d)}catch(f){N(e);if(!(f instanceof F))throw f;R(1,0)}}
function Qd(a,b,c){var d=K();try{Q(a)(b,c)}catch(e){N(d);if(!(e instanceof F))throw e;R(1,0)}}function Ad(a,b,c,d){var e=K();try{return Q(a)(b,c,d)}catch(f){N(e);if(!(f instanceof F))throw f;R(1,0)}}function Dd(a,b,c,d,e,f){var g=K();try{return Q(a)(b,c,d,e,f)}catch(h){N(g);if(!(h instanceof F))throw h;R(1,0)}}function ce(a,b,c,d,e,f){var g=K();try{Q(a)(b,c,d,e,f)}catch(h){N(g);if(!(h instanceof F))throw h;R(1,0)}}
function Ed(a,b,c,d,e,f,g){var h=K();try{return Q(a)(b,c,d,e,f,g)}catch(k){N(h);if(!(k instanceof F))throw k;R(1,0)}}function Bd(a,b,c,d,e){var f=K();try{return Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}function Rd(a,b,c,d){var e=K();try{Q(a)(b,c,d)}catch(f){N(e);if(!(f instanceof F))throw f;R(1,0)}}function Sd(a,b,c,d,e){var f=K();try{Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}
function zd(a,b,c,d){var e=K();try{return Q(a)(b,c,d)}catch(f){N(e);if(!(f instanceof F))throw f;R(1,0)}}function Od(a,b,c){var d=K();try{Q(a)(b,c)}catch(e){N(d);if(!(e instanceof F))throw e;R(1,0)}}function ud(a,b,c,d,e){var f=K();try{return Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}function rd(a,b){var c=K();try{return Q(a)(b)}catch(d){N(c);if(!(d instanceof F))throw d;R(1,0)}}
function he(a,b,c,d,e,f,g,h,k,m,p){var n=K();try{Q(a)(b,c,d,e,f,g,h,k,m,p)}catch(q){N(n);if(!(q instanceof F))throw q;R(1,0)}}function de(a,b,c,d,e,f,g){var h=K();try{Q(a)(b,c,d,e,f,g)}catch(k){N(h);if(!(k instanceof F))throw k;R(1,0)}}function ee(a,b,c,d,e,f,g,h){var k=K();try{Q(a)(b,c,d,e,f,g,h)}catch(m){N(k);if(!(m instanceof F))throw m;R(1,0)}}function sd(a,b,c){var d=K();try{return Q(a)(b,c)}catch(e){N(d);if(!(e instanceof F))throw e;R(1,0)}}
function Ud(a,b,c,d,e){var f=K();try{Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}function Wd(a,b,c,d,e){var f=K();try{Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}function Pd(a,b,c,d,e){var f=K();try{Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0)}}function Zd(a,b,c,d,e,f,g,h){var k=K();try{Q(a)(b,c,d,e,f,g,h)}catch(m){N(k);if(!(m instanceof F))throw m;R(1,0)}}
function Xd(a,b,c,d,e,f,g,h,k,m){var p=K();try{Q(a)(b,c,d,e,f,g,h,k,m)}catch(n){N(p);if(!(n instanceof F))throw n;R(1,0)}}function Yd(a,b,c,d,e,f,g,h,k){var m=K();try{Q(a)(b,c,d,e,f,g,h,k)}catch(p){N(m);if(!(p instanceof F))throw p;R(1,0)}}function ae(a,b,c,d,e,f){var g=K();try{Q(a)(b,c,d,e,f)}catch(h){N(g);if(!(h instanceof F))throw h;R(1,0)}}function $d(a,b,c,d,e,f,g){var h=K();try{Q(a)(b,c,d,e,f,g)}catch(k){N(h);if(!(k instanceof F))throw k;R(1,0)}}
function je(a,b,c,d,e,f,g,h,k,m,p,n,q){var t=K();try{Q(a)(b,c,d,e,f,g,h,k,m,p,n,q)}catch(u){N(t);if(!(u instanceof F))throw u;R(1,0)}}function ie(a,b,c,d,e,f,g,h,k,m,p,n){var q=K();try{Q(a)(b,c,d,e,f,g,h,k,m,p,n)}catch(t){N(q);if(!(t instanceof F))throw t;R(1,0)}}function ge(a,b,c,d,e,f,g,h,k,m){var p=K();try{Q(a)(b,c,d,e,f,g,h,k,m)}catch(n){N(p);if(!(n instanceof F))throw n;R(1,0)}}
function fe(a,b,c,d,e,f,g,h,k){var m=K();try{Q(a)(b,c,d,e,f,g,h,k)}catch(p){N(m);if(!(p instanceof F))throw p;R(1,0)}}function ke(a,b,c,d,e,f,g,h,k,m,p,n,q,t){var u=K();try{Q(a)(b,c,d,e,f,g,h,k,m,p,n,q,t)}catch(y){N(u);if(!(y instanceof F))throw y;R(1,0)}}function Td(a,b,c,d,e,f){var g=K();try{Q(a)(b,c,d,e,f)}catch(h){N(g);if(!(h instanceof F))throw h;R(1,0)}}function Fd(a,b,c,d,e,f,g,h){var k=K();try{return Q(a)(b,c,d,e,f,g,h)}catch(m){N(k);if(!(m instanceof F))throw m;R(1,0)}}
function Kd(a,b){var c=K();try{return Q(a)(b)}catch(d){N(c);if(!(d instanceof F))throw d;R(1,0);return 0n}}function Id(a,b,c,d,e,f,g,h,k,m,p,n,q){var t=K();try{return Q(a)(b,c,d,e,f,g,h,k,m,p,n,q)}catch(u){N(t);if(!(u instanceof F))throw u;R(1,0)}}function Ld(a,b,c,d,e){var f=K();try{return Q(a)(b,c,d,e)}catch(g){N(f);if(!(g instanceof F))throw g;R(1,0);return 0n}}function vd(a,b,c,d){var e=K();try{return Q(a)(b,c,d)}catch(f){N(e);if(!(f instanceof F))throw f;R(1,0)}}
function Gd(a,b,c,d,e,f,g,h,k,m,p){var n=K();try{return Q(a)(b,c,d,e,f,g,h,k,m,p)}catch(q){N(n);if(!(q instanceof F))throw q;R(1,0)}}function Hd(a,b,c,d,e,f,g,h,k,m,p,n){var q=K();try{return Q(a)(b,c,d,e,f,g,h,k,m,p,n)}catch(t){N(q);if(!(t instanceof F))throw t;R(1,0)}}function le(a,b,c,d,e,f,g,h,k,m,p,n,q,t,u,y){var C=K();try{Q(a)(b,c,d,e,f,g,h,k,m,p,n,q,t,u,y)}catch(L){N(C);if(!(L instanceof F))throw L;R(1,0)}}
function Jd(a,b,c,d,e,f){var g=K();try{return Q(a)(b,c,d,e,f)}catch(h){N(g);if(!(h instanceof F))throw h;R(1,0)}}function Cd(a,b,c,d,e,f){var g=K();try{return Q(a)(b,c,d,e,f)}catch(h){N(g);if(!(h instanceof F))throw h;R(1,0)}}function Qi(a=[]){var b=Hf("main").Pa;if(b){a.unshift(ha);var c=a.length,d=Je(4*(c+1)),e=d;a.forEach(g=>{D[e>>2]=Ug(g);e+=4});D[e>>2]=0;try{var f=b(c,d);cd(f,!0)}catch(g){re(g)}}}
function Ri(a=fa){function b(){l.calledRun=!0;if(!ta&&(Sa(),aa(l),l.onRuntimeInitialized?.(),l.noInitialRun||Qi(a),!r)){if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var c=l.postRun.shift();kf.push(c)}Ta(kf)}}if(0<Va)Wa=Ri;else if(r)aa(l),Sa();else{if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)Ae.push(l.preRun.shift());Ta(Ae);0<Va?Wa=Ri:l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),
1);b()},1)):b()}}if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();Ri();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Vips;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Vips;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Vips);
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && Vips();
