#!/bin/sh
set -euo pipefail
/var/task/erlang/bin/erl -noshell -s mainb loop -s init stop +P 1024 +Q 1024 +swct very_lazy +Mea min
# +S 1 SDio 1
# -mode minimal

    # -noshell
    # +Mea min \          # turns off many memory allocators
    # +swct very_lazy     # reduces garbage collection frequency

    # +S Schedulers:SchedulerOnline, max 1024:1024, default 1:1
    # +SDio DirtyIOSchedulers, 1-1024, default 10
    # +P MaxSimultaneouslyExistingProcesses, 1024-134,217,727
    # +Q MaxSimultaneouslyExistingPorts, 1024-134,217,727

    # -s mainb loop \     # runs this script
    # -s init stop        # ends

    # -mode minimal    : does not requires a boot script ( embedded, does ) : does not work on ( Lambda arm64 )
    # -boot start_clean : one of the provided boot scripts

